//! Pre-generated list of fallback directories.
//!
//! This list is derived from the list that ships with Tor, and
//! kludged up with a quick and dirty script.  Never use it directly;
//! instead use [`super::FallbackSet`].

use tor_llcrypto::pk::ed25519::Ed25519Identity;
use tor_llcrypto::pk::rsa::RSAIdentity;

/// String representation for a fallback directory
pub(super) struct FallbackDir {
    /// RSA identity in hexadecimal
    rsa_identity: &'static str,
    /// Ed25519 identity in base 64
    ed_identity: &'static str,
    /// IPv4 address:port
    ipv4_orport: &'static str,
    /// IPv6 [address]:port, if there is one.
    ipv6_orport: Option<&'static str>,
}

impl From<&FallbackDir> for super::FallbackDir {
    fn from(fb: &FallbackDir) -> super::FallbackDir {
        // We use "unwrap" here because these provided values are given
        // as part of the source.
        let rsa_identity = hex::decode(fb.rsa_identity).unwrap();
        let rsa_identity = RSAIdentity::from_bytes(&rsa_identity).unwrap();
        let ed_identity = base64::decode(fb.ed_identity).unwrap();
        let ed_identity = Ed25519Identity::from_bytes(&ed_identity).unwrap();

        let mut orports = Vec::new();
        orports.push(fb.ipv4_orport.parse().unwrap());
        if let Some(ipv6_orport) = fb.ipv6_orport {
            orports.push(ipv6_orport.parse().unwrap());
        }
        super::FallbackDir {
            rsa_identity,
            ed_identity,
            orports,
        }
    }
}

/// List of all known fallback directories, in string format.
// Generated by a python script using stem and the current tor fallback
// list.  Anything that wasn't listed on 16 Nov 2020 didn't make it in here.
//
// TODO: Replace this with a better list.
pub(super) const FALLBACKS: &[FallbackDir] = &[
    FallbackDir {
        rsa_identity: "0338F9F55111FE8E3570E7DE117EF3AF999CC1D7",
        ed_identity: "GsyBNDtZ8A3X++jOPpNWDJaDXFetH0qbXaqzxp3vWbI",
        ipv4_orport: "185.225.17.3:443",
        ipv6_orport: Some("[2a0a:c800:1:5::3]:443"),
    },
    FallbackDir {
        rsa_identity: "03C3069E814E296EB18776EB61B1ECB754ED89FE",
        ed_identity: "5nP3zlhsox/Q3U9etQ+zrWINQPNzc8OOwV/kbnK4NZU",
        ipv4_orport: "81.7.10.193:993",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "0C475BA4D3AA3C289B716F95954CAD616E50C4E5",
        ed_identity: "dio9Dfc+qWuvUnJJERmEflb8qycXnrXVkjS4ecXhZrs",
        ipv4_orport: "81.7.18.7:9001",
        ipv6_orport: Some("[2a02:180:6:1::2eee]:9001"),
    },
    FallbackDir {
        rsa_identity: "0F6E5CA4BF5565D9AA9FDDCA165AFC6A5305763D",
        ed_identity: "1FdOnRvYuHpggwoSjbhiAk9oo2JUCGYTfAyMHRATCzM",
        ipv4_orport: "193.234.15.60:443",
        ipv6_orport: Some("[2a00:1c20:4089:1234:67bc:79f3:61c0:6e49]:443"),
    },
    FallbackDir {
        rsa_identity: "113143469021882C3A4B82F084F8125B08EE471E",
        ed_identity: "TMzMEPui071YlaOG8EzlT9a5YrlI//59DL+5VRn8d5k",
        ipv4_orport: "93.177.67.71:8080",
        ipv6_orport: Some("[2a03:4000:38:559::2]:8080"),
    },
    FallbackDir {
        rsa_identity: "11DF0017A43AF1F08825CD5D973297F81AB00FF3",
        ed_identity: "fgDwY4AcdAv5DM05wam5hoD0jslTeU3Q8ETAx4GPGvk",
        ipv4_orport: "37.120.174.249:443",
        ipv6_orport: Some("[2a03:4000:6:724c:df98:15f9:b34d:443]:443"),
    },
    FallbackDir {
        rsa_identity: "12AD30E5D25AA67F519780E2111E611A455FDC89",
        ed_identity: "fejD+zy4mgihice7QP/LvGdrUdJabMwGa+lmNF9Kp+Q",
        ipv4_orport: "193.11.114.43:9001",
        ipv6_orport: Some("[2001:6b0:30:1000::99]:9050"),
    },
    FallbackDir {
        rsa_identity: "12FD624EE73CEF37137C90D38B2406A66F68FAA2",
        ed_identity: "qoVxOXoWz+T+ngAf32fIQDCwTKCSGeFj0rZNE1YyqP0",
        ipv4_orport: "37.157.195.87:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "158581827034DEF1BAB1FC248D180165452E53D3",
        ed_identity: "gthdSWvrzfj1SJ5LUDc6Xuxv6wLGvlSa7YnZrZPSLBM",
        ipv4_orport: "193.234.15.61:443",
        ipv6_orport: Some("[2a00:1c20:4089:1234:2712:a3d0:666b:88a6]:443"),
    },
    FallbackDir {
        rsa_identity: "15BE17C99FACE24470D40AF782D6A9C692AB36D6",
        ed_identity: "DPvwZRCFlEXzfRT1SBe+hIyiP0UeW2J2wM/HHQeSFn8",
        ipv4_orport: "51.15.78.0:9001",
        ipv6_orport: Some("[2001:bc8:1824:c4b::1]:9001"),
    },
    FallbackDir {
        rsa_identity: "185F2A57B0C4620582602761097D17DB81654F70",
        ed_identity: "bAQa7y4SFhpgb4B0zom+mJoHqfnyL5tbt2RbSV18Idc",
        ipv4_orport: "204.11.50.131:9001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "1CD17CB202063C51C7DAD3BACEF87ECE81C2350F",
        ed_identity: "p2d7Z7R3PCK3Y/DDQTNBaXdksASEdTaD+V7I2BIWWKI",
        ipv4_orport: "50.7.74.171:9001",
        ipv6_orport: Some("[2001:49f0:d002:2::51]:443"),
    },
    FallbackDir {
        rsa_identity: "1F6ABD086F40B890A33C93CC4606EE68B31C9556",
        ed_identity: "DcZZHUOmJ+FNRj7xgecpAML/sjGBu4JYZr3CceHDL88",
        ipv4_orport: "199.184.246.250:443",
        ipv6_orport: Some("[2620:124:1009:1::171]:443"),
    },
    FallbackDir {
        rsa_identity: "20462CBA5DA4C2D963567D17D0B7249718114A68",
        ed_identity: "Z/yFHI658azdnKU3Dz0Susfnc4Y0CKmpP7jzqoyNxp4",
        ipv4_orport: "212.47.229.2:9001",
        ipv6_orport: Some("[2001:bc8:47ac:23a::1]:9001"),
    },
    FallbackDir {
        rsa_identity: "204DFD2A2C6A0DC1FA0EACB495218E0B661704FD",
        ed_identity: "O2ddyzT3VejqK7/rH2WM6iUR2HeGUf3NYGdNYj3LFIM",
        ipv4_orport: "77.247.181.164:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "24D0491A2ADAAB52C17625FBC926D84477AEA322",
        ed_identity: "r7vuNUryeNm+Qw9886C9uE4o5rBYCXPxhA3I+gpHGzU",
        ipv4_orport: "193.234.15.57:443",
        ipv6_orport: Some("[2a00:1c20:4089:1234:7825:2c5d:1ecd:c66f]:443"),
    },
    FallbackDir {
        rsa_identity: "28F4F392F8F19E3FBDE09616D9DB8143A1E2DDD3",
        ed_identity: "4M/pCad2pYGL7OJUeRWJYE8S1f32QUVY0iLoNKb8T5Q",
        ipv4_orport: "185.220.101.137:10137",
        ipv6_orport: Some("[2a0b:f4c2:1::137]:10137"),
    },
    FallbackDir {
        rsa_identity: "2BA2C8E96B2590E1072AECE2BDB5C48921BF8510",
        ed_identity: "0c93jN2vfAgY9dryGcGu/OahU6MVroE3FRU0aKpoxc0",
        ipv4_orport: "138.201.250.33:9011",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "2BB85DC5BD3C6F0D81A4F2B5882176C6BF7ECF5A",
        ed_identity: "Nw2I+2Lsv3CX8jEY9GJkf1jGkbq6a2zDaMn0G10rjkk",
        ipv4_orport: "5.181.50.99:443",
        ipv6_orport: Some("[2a03:4000:3f:16c:3851:6bff:fe07:bd2]:443"),
    },
    FallbackDir {
        rsa_identity: "2F0F32AB1E5B943CA7D062C03F18960C86E70D94",
        ed_identity: "CphtNy4/DfqEe5XX9NWzR15VdhfYvtQL42+cCxr2o/I",
        ipv4_orport: "97.74.237.196:9001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "311A4533F7A2415F42346A6C8FA77E6FD279594C",
        ed_identity: "gjYpaXjgfL6R5H0L5/kPC7KRQReaQ/HXTqRbSI1H+PQ",
        ipv4_orport: "94.230.208.147:8443",
        ipv6_orport: Some("[2a02:418:6017::147]:8443"),
    },
    FallbackDir {
        rsa_identity: "32EE911D968BE3E016ECA572BB1ED0A9EE43FC2F",
        ed_identity: "VsG0z6PR8T7s3HsOSBvBgD6WL4NBa219n04u+Qc/9RQ",
        ipv4_orport: "109.105.109.162:60784",
        ipv6_orport: Some("[2001:948:7:2::163]:5001"),
    },
    FallbackDir {
        rsa_identity: "330CD3DB6AD266DC70CDB512B036957D03D9BC59",
        ed_identity: "zV1cBIQeQNP+D7E/o7QFwZkR656FnThzbHMXNIQlflk",
        ipv4_orport: "185.100.84.212:443",
        ipv6_orport: Some("[2a06:1700:0:7::1]:443"),
    },
    FallbackDir {
        rsa_identity: "375DCBB2DBD94E5263BC0C015F0C9E756669617E",
        ed_identity: "gERhugbL6dbAvWTQCEIozBw9QSEH5fTuqWbb8Jtjyc0",
        ipv4_orport: "64.79.152.132:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "39F096961ED2576975C866D450373A9913AFDC92",
        ed_identity: "8fN2IHdgryRlXZbRLcvvBhMaYDRo8zCAIE0d/C+wOpU",
        ipv4_orport: "198.50.191.95:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "3AFDAAD91A15B4C6A7686A53AA8627CA871FF491",
        ed_identity: "nbArRRyMh7DBRLr7XZuYP4hmZH4XVJ1gXc0nMZTNQZQ",
        ipv4_orport: "50.7.74.174:9001",
        ipv6_orport: Some("[2001:49f0:d002:2::57]:443"),
    },
    FallbackDir {
        rsa_identity: "3C79699D4FBC37DE1A212D5033B56DAE079AC0EF",
        ed_identity: "ZiTuTLaLEQjxq9bOD9c+dXAQhay6iAmUhs3DOmG+C40",
        ipv4_orport: "212.83.154.33:443",
        ipv6_orport: Some("[2001:bc8:31d3:1dd::1]:443"),
    },
    FallbackDir {
        rsa_identity: "3CB4193EF4E239FCEDC4DC43468E0B0D6B67ACC3",
        ed_identity: "3c5koajx8IV5RkBuLlll7KonUyZfmkHjeTYk0sijGdw",
        ipv4_orport: "51.38.65.160:9001",
        ipv6_orport: Some("[2001:41d0:801:2000::f6e]:9001"),
    },
    FallbackDir {
        rsa_identity: "3CCF9573F59137E52787D9C322AC19D2BD090B70",
        ed_identity: "onVQbM8ogjPrUyC9b3uW88D/u3kvkrJS3hC0xkSWgFE",
        ipv4_orport: "95.216.211.81:443",
        ipv6_orport: Some("[2a01:4f9:c010:4dfa::1]:443"),
    },
    FallbackDir {
        rsa_identity: "3E53D3979DB07EFD736661C934A1DED14127B684",
        ed_identity: "extACn0DLTFq98Ni2q+XtvqFgkv0Sti0T1fK9kTaBqk",
        ipv4_orport: "217.79.179.177:9001",
        ipv6_orport: Some("[2001:4ba0:fff9:131:6c4f::90d3]:9001"),
    },
    FallbackDir {
        rsa_identity: "4061C553CA88021B8302F0814365070AAE617270",
        ed_identity: "xBGINMKnI6dvQLVPgb6bhzuzaIGvLw2Cpy2ZyZYmON4",
        ipv4_orport: "185.100.85.101:9001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "4623A9EC53BFD83155929E56D6F7B55B5E718C24",
        ed_identity: "TeDcUhWw+XxhYPN/bDJqvxYL7yg6p8cPmRLa5UOB9Ho",
        ipv4_orport: "163.172.157.213:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "484A10BA2B8D48A5F0216674C8DD50EF27BC32F3",
        ed_identity: "sVTDglBln5kKGfpYI9bhRh8dNneCQsNjtCxoKUwqg7Y",
        ipv4_orport: "193.70.43.76:9001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "4BFC9C631A93FF4BA3AA84BC6931B4310C38A263",
        ed_identity: "xbDOU2WblscuIxu56QULiZ3zXXyL1vqf/lvmHECtgg8",
        ipv4_orport: "109.70.100.4:443",
        ipv6_orport: Some("[2a03:e600:100::4]:443"),
    },
    FallbackDir {
        rsa_identity: "4F0DB7E687FC7C0AE55C8F243DA8B0EB27FBF1F2",
        ed_identity: "7nRRGsJYe3/OEGWh1u92yJq836jaMIqsGUMCVuUfxGs",
        ipv4_orport: "108.53.208.157:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "509EAB4C5D10C9A9A24B4EA0CE402C047A2D64E6",
        ed_identity: "O1MbXsxCb4A9rI/I6bnPI3Ds+XdncoMOSmTakJRAZrU",
        ipv4_orport: "5.9.158.75:9001",
        ipv6_orport: Some("[2a01:4f8:190:514a::2]:9001"),
    },
    FallbackDir {
        rsa_identity: "510176C07005D47B23E6796F02C93241A29AA0E9",
        ed_identity: "pkYjVpn6VIanyRogxcPemmlnL10ygM3tbTscSBiWfg8",
        ipv4_orport: "69.30.215.42:443",
        ipv6_orport: Some("[2604:4300:a:2e:21b:21ff:fe11:392]:443"),
    },
    FallbackDir {
        rsa_identity: "5262556D44A7F2434990FDE1AE7973C67DF49E58",
        ed_identity: "gAE5yi9lNflnXFFOVyzzN7wLXJ16oBrQ2btSqt5fI/g",
        ipv4_orport: "176.223.141.106:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "52BFADA8BEAA01BA46C8F767F83C18E2FE50C1B9",
        ed_identity: "3Kvdb93+PpBhSP2sXLHQ4xdYAqyTN9YI7mY5pCi1LjQ",
        ipv4_orport: "85.25.159.65:80",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "562434D987CF49D45649B76ADCA993BEA8F78471",
        ed_identity: "p8uVzfZwfOFIgd6XdUOJNL0PfRq/YmkpvMLTam383vg",
        ipv4_orport: "193.234.15.59:443",
        ipv6_orport: Some("[2a00:1c20:4089:1234:bff6:e1bb:1ce3:8dc6]:443"),
    },
    FallbackDir {
        rsa_identity: "578E007E5E4535FBFEF7758D8587B07B4C8C5D06",
        ed_identity: "qm5XHTSZpVLD/fHmAUyUuAgzQszQFaFqLcIZXzExctM",
        ipv4_orport: "89.234.157.254:443",
        ipv6_orport: Some("[2001:67c:2608::1]:443"),
    },
    FallbackDir {
        rsa_identity: "5E56738E7F97AA81DEEF59AF28494293DFBFCCDF",
        ed_identity: "bLETd6FA4/k3KwSz9m01uC6MGdU9ZXtuOziW1vpgc+k",
        ipv4_orport: "172.98.193.43:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "68F175CCABE727AA2D2309BCD8789499CEE36ED7",
        ed_identity: "sLGgkmWZCZAogV18gdFjBupGv3xma8cVuudnASz4v6Q",
        ipv4_orport: "163.172.139.104:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "6A7551EEE18F78A9813096E82BF84F740D32B911",
        ed_identity: "798fdg7DGJ+m3YLNr9tuvcQCYe+OHdloWpttAhj+Vjc",
        ipv4_orport: "95.217.16.212:443",
        ipv6_orport: Some("[2a01:4f9:c010:609a::1]:443"),
    },
    FallbackDir {
        rsa_identity: "72B2B12A3F60408BDBC98C6DF53988D3A0B3F0EE",
        ed_identity: "PM9wXJmS/7VkrbNSSdq4nH7ig9VDRcTJYTu/qN1DYqo",
        ipv4_orport: "85.235.250.88:443",
        ipv6_orport: Some("[2a01:3a0:1:1900:85:235:250:88]:443"),
    },
    FallbackDir {
        rsa_identity: "742C45F2D9004AADE0077E528A4418A6A81BC2BA",
        ed_identity: "4Csh1Bs+xkBnbymEFzuND5JRXo05CbgaB5m+CH7WEGw",
        ipv4_orport: "178.17.170.23:9001",
        ipv6_orport: Some("[2a00:1dc0:caff:7d::8254]:9001"),
    },
    FallbackDir {
        rsa_identity: "7600680249A22080ECC6173FBBF64D6FCF330A61",
        ed_identity: "np89gXLD3ufDOjtjZBimLuRTiWhSdqX2Y1OTqJuUSLE",
        ipv4_orport: "81.7.14.31:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "7614EF326635DA810638E2F5D449D10AE2BB7158",
        ed_identity: "TTkpUcQtaWnpzrRzV19jYQbSUyW5qd23+jnMHJoC9sU",
        ipv4_orport: "62.171.144.155:443",
        ipv6_orport: Some("[2a02:c207:3004:8874::1]:443"),
    },
    FallbackDir {
        rsa_identity: "77131D7E2EC1CA9B8D737502256DA9103599CE51",
        ed_identity: "V3itvRTciIQRaO+chK6IjeUbv/dCso9e/8Q41OIEuUc",
        ipv4_orport: "77.247.181.166:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "775B0FAFDE71AADC23FFC8782B7BEB1D5A92733E",
        ed_identity: "hXPwzzXofHvVgMImcWAaJRIhudrOGPNvtCFlkYxMZNA",
        ipv4_orport: "5.196.23.64:9001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "79509683AB4C8DDAF90A120C69A4179C6CD5A387",
        ed_identity: "ou9JQi/To8KzH9VWO3DSqgjnWV2m63IDYH7zB1Hty5E",
        ipv4_orport: "185.244.193.141:9001",
        ipv6_orport: Some("[2a03:4000:27:192:24:12:1984:4]:9001"),
    },
    FallbackDir {
        rsa_identity: "7BB70F8585DFC27E75D692970C0EEB0F22983A63",
        ed_identity: "iibuh5uywUapIP8+IytB9UJjopKVd73/BJf0yQvGazw",
        ipv4_orport: "51.254.136.195:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "7BFB908A3AA5B491DA4CA72CCBEE0E1F2A939B55",
        ed_identity: "WkViAVHwT01UufFFaG2nHVOAwXqRrRDUOdiwbfB2B+w",
        ipv4_orport: "77.247.181.162:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "80AAF8D5956A43C197104CEF2550CD42D165C6FB",
        ed_identity: "TkKHt6XxoQh6urm/xudkFG51kp4bs9RnQRyjbzvUAQc",
        ipv4_orport: "193.11.114.45:9002",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "8101421BEFCCF4C271D5483C5AABCAAD245BBB9D",
        ed_identity: "dsg5Mu1OJzYpttfMDYSWF4dxLEdFivvbxYXmq6AeBpY",
        ipv4_orport: "51.254.96.208:9001",
        ipv6_orport: Some("[2001:41d0:401:3100::30dc]:9001"),
    },
    FallbackDir {
        rsa_identity: "8111FEB45EF2950EB8F84BFD8FF070AB07AEE9DD",
        ed_identity: "96u8ADx3igfVLI6mHJ4HCNmp7UgZDFPTxi3DxBogv9k",
        ipv4_orport: "152.89.106.147:9001",
        ipv6_orport: Some("[2a03:4000:39:605:c4f2:c9ff:fe64:c215]:9001"),
    },
    FallbackDir {
        rsa_identity: "81B75D534F91BFB7C57AB67DA10BCEF622582AE8",
        ed_identity: "r4SmC/yRVvtx+IAK5rWuhArd7H8ffYuY8fg+4mD2i/I",
        ipv4_orport: "192.42.116.16:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "844AE9CAD04325E955E2BE1521563B79FE7094B7",
        ed_identity: "VttOakBYLTZyvVYL4TC9w0lyUGMx0L1gxVsrGUqSato",
        ipv4_orport: "192.87.28.82:9001",
        ipv6_orport: Some("[2001:678:230:3028:192:87:28:82]:9001"),
    },
    FallbackDir {
        rsa_identity: "855BC2DABE24C861CD887DB9B2E950424B49FC34",
        ed_identity: "eygZLf2qsRh/qNNDSnmm6n6yjbQ14ZCIsPyrz8t4Z3Y",
        ipv4_orport: "85.228.173.240:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "85A885433E50B1874F11CEC9BE98451E24660976",
        ed_identity: "89SDoAQyrQZgvAycXKGw7SO77svcItXDvq35YRbUvjw",
        ipv4_orport: "178.254.7.88:8443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "8C00FA7369A7A308F6A137600F0FA07990D9D451",
        ed_identity: "L23HctgabSrEUrcIPyn57lbLCb6h0TOxoYlLovViM4I",
        ipv4_orport: "163.172.194.53:9001",
        ipv6_orport: Some("[2001:bc8:225f:142:6c69:7461:7669:73]:9001"),
    },
    FallbackDir {
        rsa_identity: "8CAA470B905758742203E3EB45941719FCA9FEEC",
        ed_identity: "GOC0nmuoMP3c+cpu+iejBmfnw82ySyQJQP+g76QA4cw",
        ipv4_orport: "188.138.102.98:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "8CF987FF43FB7F3D9AA4C4F3D96FFDF247A9A6C2",
        ed_identity: "cfUdtrPAWE4n1l+m0xiXHPiQaX9+b1JYEnsqzSdyA3M",
        ipv4_orport: "109.70.100.6:443",
        ipv6_orport: Some("[2a03:e600:100::6]:443"),
    },
    FallbackDir {
        rsa_identity: "8D79F73DCD91FC4F5017422FAC70074D6DB8DD81",
        ed_identity: "ZU9W1bA+8qY6At4zhtVyCQF2Y3AC4GA1oo6wKhDyI7Q",
        ipv4_orport: "5.189.169.190:8080",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "8E6EDA78D8E3ABA88D877C3E37D6D4F0938C7B9F",
        ed_identity: "+cA5po9F08p5F+FsyKqfruH80jejDstEQ0sH7CWvBkM",
        ipv4_orport: "80.67.172.162:443",
        ipv6_orport: Some("[2001:910:1410:600::1]:443"),
    },
    FallbackDir {
        rsa_identity: "90A5D1355C4B5840E950EB61E673863A6AE3ACA1",
        ed_identity: "OJfFhITpQ0/LsIIcRHh7/w84RNfyAN9zFrUmEb4bNbY",
        ipv4_orport: "54.37.139.118:9001",
        ipv6_orport: Some("[2001:41d0:601:1100::1b8]:9001"),
    },
    FallbackDir {
        rsa_identity: "924B24AFA7F075D059E8EEB284CC400B33D3D036",
        ed_identity: "7wdm7KIialbA+W4rV3PTbG9w6XHvuHiFTHvzNyQ3LWQ",
        ipv4_orport: "96.253.78.108:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "9661AC95717798884F3E3727D360DD98D66727CC",
        ed_identity: "9qduBqJiROiPxgec0lcTEWj2aNaCyNAz1oHDZ8SnJcw",
        ipv4_orport: "109.70.100.5:443",
        ipv6_orport: Some("[2a03:e600:100::5]:443"),
    },
    FallbackDir {
        rsa_identity: "99E246DB480B313A3012BC3363093CC26CD209C7",
        ed_identity: "eF/zzvy2OSESbJ7aBF68nk83EOWRt1NunRfkJxY8bOU",
        ipv4_orport: "173.212.254.192:31337",
        ipv6_orport: Some("[2a02:c207:3002:3972::1]:31337"),
    },
    FallbackDir {
        rsa_identity: "9B2BC7EFD661072AFADC533BE8DCF1C19D8C2DCC",
        ed_identity: "u7iwx1/7QZGzKblwR5uf1k8T+RgHxwaUJb4y07AENVI",
        ipv4_orport: "188.127.69.60:443",
        ipv6_orport: Some("[2a02:29d0:8008:c0de:bad:beef::]:443"),
    },
    FallbackDir {
        rsa_identity: "9B31F1F1C1554F9FFB3455911F82E818EF7C7883",
        ed_identity: "SA5XFaUqDUFwBwKCdBqpUli5k3mdUuVNUG5jtNQGtd4",
        ipv4_orport: "185.100.86.128:9001",
        ipv6_orport: Some("[2a06:1700:1::11]:9001"),
    },
    FallbackDir {
        rsa_identity: "9BA84E8C90083676F86C7427C8D105925F13716C",
        ed_identity: "9PB8PEWF0oc4Z74g2B3LoVjNVRhFI4/Ul4e0rbd1UOk",
        ipv4_orport: "95.142.161.63:443",
        ipv6_orport: Some("[2001:4b98:dc0:47:216:3eff:fe3d:888c]:443"),
    },
    FallbackDir {
        rsa_identity: "9C900A7F6F5DD034CFFD192DAEC9CCAA813DB022",
        ed_identity: "vFZ3bEHGhGaj44H46UyKeD+fZZ0L4Ny7tliUCYGj37g",
        ipv4_orport: "86.105.212.130:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "9F7D6E6420183C2B76D3CE99624EBC98A21A967E",
        ed_identity: "5E9oJj9elOyWCgvgsUzWpjpG9T5naDb/j9Gq1Wf9aQ0",
        ipv4_orport: "46.28.110.244:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "A0F06C2FADF88D3A39AA3072B406F09D7095AC9E",
        ed_identity: "dJraGedqLgz1nPtZdmW7nFIG/u42ixfcvMKPEly0gwI",
        ipv4_orport: "46.165.230.5:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "A1B28D636A56AAFFE92ADCCA937AA4BD5333BB4C",
        ed_identity: "1HAiAGW/XjYKoJtSnDEOKFe/uRNJxwj3nl/WKd/5ooA",
        ipv4_orport: "193.234.15.55:443",
        ipv6_orport: Some("[2a00:1c20:4089:1234:7b2c:11c5:5221:903e]:443"),
    },
    FallbackDir {
        rsa_identity: "A53C46F5B157DD83366D45A8E99A244934A14C46",
        ed_identity: "s0BLh6T2Ruh9+EyOl4tRuv/zVuDxhXRk9S9ILyUjoGc",
        ipv4_orport: "128.31.0.13:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "A68097FE97D3065B1A6F4CE7187D753F8B8513F5",
        ed_identity: "adUTZoPY+JSbZZBen2N/etCSpYTiSk4lb7J7EjrcHUA",
        ipv4_orport: "212.47.233.86:9101",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "AC2BEDD0BAC72838EA7E6F113F856C4E8018ACDB",
        ed_identity: "O8HMBHhwLmdW9MQvwgHhehwCBB/5VlF92lSPXXT686I",
        ipv4_orport: "176.10.107.180:9001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "ACDD9E85A05B127BA010466C13C8C47212E8A38F",
        ed_identity: "KQdIGXATOpoGWI57h8y1uiNoPmHgLLrB/6l7HCZANJ8",
        ipv4_orport: "185.129.62.62:9001",
        ipv6_orport: Some("[2a06:d380:0:3700::62]:9001"),
    },
    FallbackDir {
        rsa_identity: "AD19490C7DBB26D3A68EFC824F67E69B0A96E601",
        ed_identity: "y8Vd9SygeMOyBkS4oLQVbC0F+9wS4NF5q1P61W80jL0",
        ipv4_orport: "188.40.128.246:9001",
        ipv6_orport: Some("[2a01:4f8:221:1ac1:dead:beef:7005:9001]:9001"),
    },
    FallbackDir {
        rsa_identity: "AD86CD1A49573D52A7B6F4A35750F161AAD89C88",
        ed_identity: "2Dlzpo/BG/ltXWCjpT/ovdHkMwkc6GB7USemxQr34R0",
        ipv4_orport: "176.10.104.240:8443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "B06F093A3D4DFAD3E923F4F28A74901BD4F74EB1",
        ed_identity: "gLcNnVDNfnWsOPH5MvqkPyn2G+5RkbtBazOuxisZebI",
        ipv4_orport: "178.17.174.14:9001",
        ipv6_orport: Some("[2a00:1dc0:caff:8b::5b9a]:9001"),
    },
    FallbackDir {
        rsa_identity: "B143D439B72D239A419F8DCE07B8A8EB1B486FA7",
        ed_identity: "K6u+G8wlQS7cMU1QuO4roeUHlj27AbLZMz7a1SriTlk",
        ipv4_orport: "212.129.62.232:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "B27CF1DCEECD50F7992B07D720D7F6BF0EDF9D40",
        ed_identity: "GkEC42Zfp2ZpdkXV/ujA1HhnvpbVbVgOSyl9LDS9es4",
        ipv4_orport: "109.70.100.2:443",
        ipv6_orport: Some("[2a03:e600:100::2]:443"),
    },
    FallbackDir {
        rsa_identity: "B5212DB685A2A0FCFBAE425738E478D12361710D",
        ed_identity: "T8YqK61rrWPdqYfh2r15KPi/zndb4AdPfATuDvsBQ4I",
        ipv4_orport: "93.115.97.242:9001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "B83DC1558F0D34353BB992EF93AFEAFDB226A73E",
        ed_identity: "E22eTrwjkzB05dyqfKAQBgf6VSDa8DRo7kvK0KqFsV0",
        ipv4_orport: "193.11.114.46:9003",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "B84F248233FEA90CAD439F292556A3139F6E1B82",
        ed_identity: "3uXoHujMGuaUmafqNEKMxdPmYVNZaSMuQSK3y/MOGMc",
        ipv4_orport: "85.248.227.164:9002",
        ipv6_orport: Some("[2a00:1298:8011:212::164]:9004"),
    },
    FallbackDir {
        rsa_identity: "BCEDF6C193AA687AE471B8A22EBF6BC57C2D285E",
        ed_identity: "zeqbk9w8A3npye2MknX1bn9MvkIRZANMaNi/JOsHmtc",
        ipv4_orport: "198.96.155.3:5001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "BCEF908195805E03E92CCFE669C48738E556B9C5",
        ed_identity: "R7L4DDl4sTAMZraCSo+GTcf6b6VatZmVbVbHj4691oM",
        ipv4_orport: "128.199.55.207:9001",
        ipv6_orport: Some("[2a03:b0c0:2:d0::158:3001]:9001"),
    },
    FallbackDir {
        rsa_identity: "BD552C165E2ED2887D3F1CCE9CFF155DDA2D86E6",
        ed_identity: "ugnOtWVnu78sNpHQU0oOH87SCjQjRlj8EgyW+8+HuP8",
        ipv4_orport: "213.141.138.174:50001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "BF0FB582E37F738CD33C3651125F2772705BB8E8",
        ed_identity: "JltQ+aH5D+ZputfajsDp/4G11SPDPSrPComyMc56ALg",
        ipv4_orport: "148.251.190.229:9010",
        ipv6_orport: Some("[2a01:4f8:211:c68::2]:9010"),
    },
    FallbackDir {
        rsa_identity: "BF735F669481EE1CCC348F0731551C933D1E2278",
        ed_identity: "uxbIFPX2Rnd8yY1ngXHXdDHcShiLNtaEQKLU0XD2kk4",
        ipv4_orport: "212.47.233.250:9001",
        ipv6_orport: Some("[2001:bc8:4400:2b00::1c:629]:9001"),
    },
    FallbackDir {
        rsa_identity: "C0C4F339046EB824999F711D178472FDF53BE7F5",
        ed_identity: "QlaVAsXYIvGdWJoYwo5fi1MtJ3bQ5plaUjk7NNPVjcQ",
        ipv4_orport: "132.248.241.5:9101",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "C282248597D1C8522A2A7525E61C8B77BBC37614",
        ed_identity: "wcOYEvHFHT2Nxc+tlzFsklyJtOcc9ckWdBBur+M0SNE",
        ipv4_orport: "109.70.100.3:443",
        ipv6_orport: Some("[2a03:e600:100::3]:443"),
    },
    FallbackDir {
        rsa_identity: "C36A434DB54C66E1A97A5653858CE36024352C4D",
        ed_identity: "Do0iSNhmPRZU/+vhgczA9Tgg95uKbagg+1JmAreA4BI",
        ipv4_orport: "50.7.74.170:9001",
        ipv6_orport: Some("[2001:49f0:d002:2::59]:443"),
    },
    FallbackDir {
        rsa_identity: "C414F28FD2BEC1553024299B31D4E726BEB8E788",
        ed_identity: "zr/I8nO0QNvwYJVAJfwEDg1xnQV0xQFsxhovyGidoPk",
        ipv4_orport: "188.138.112.60:1521",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "C656B41AEFB40A141967EBF49D6E69603C9B4A11",
        ed_identity: "+tt2zAB+flZdk/xAhZMZ//7WUKDmWT6ZQPrmcDsfcN8",
        ipv4_orport: "178.20.55.18:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "C793AB88565DDD3C9E4C6F15CCB9D8C7EF964CE9",
        ed_identity: "Ge0Ts9wi1SVLmpNEmNOP/UQF+ya+AC4ef85oG+V443Y",
        ipv4_orport: "85.248.227.163:9001",
        ipv6_orport: Some("[2a00:1298:8011:212::163]:9003"),
    },
    FallbackDir {
        rsa_identity: "C87A4D8B534F78FDF0F4639B55F121401FEF259C",
        ed_identity: "i7X2WHCX6qEpIVOIBW0WFfftnTgh4SGLON8y2bJmttU",
        ipv4_orport: "50.7.74.173:443",
        ipv6_orport: Some("[2001:49f0:d002:2::54]:443"),
    },
    FallbackDir {
        rsa_identity: "CBD0D1BD110EC52963082D839AC6A89D0AE243E7",
        ed_identity: "ZhtxaAA1sDT/zv5RdBo+XfMfX8ue5myekq9IG4YA1P8",
        ipv4_orport: "176.31.103.150:9001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "CD0F9AA1A5064430B1DE8E645CBA7A502B27ED5F",
        ed_identity: "+Z4gh7IJ1d3FFPNAdujZsHwl0KWIf0D/MZmApa/6nG4",
        ipv4_orport: "193.234.15.62:443",
        ipv6_orport: Some("[2a00:1c20:4089:1234:a6a4:2926:d0af:dfee]:443"),
    },
    FallbackDir {
        rsa_identity: "CE47F0356D86CF0A1A2008D97623216D560FB0A8",
        ed_identity: "c1bbM446BkqMA3IoJsOqoJcCnQhDh7IM5oon2hdSIBU",
        ipv4_orport: "85.25.213.211:80",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "D1AFBF3117B308B6D1A7AA762B1315FD86A6B8AF",
        ed_identity: "66mkvsATOWGsNMYtnXNadREbESQsPaa39RyFK4os+E4",
        ipv4_orport: "50.7.74.172:443",
        ipv6_orport: Some("[2001:49f0:d002:2::52]:443"),
    },
    FallbackDir {
        rsa_identity: "D317C7889162E9EC4A1DA1A1095C2A0F377536D9",
        ed_identity: "EUAByQWBvSkMnQNWUlLUh2/QMxtjeRQ1XCvlv8Fkcpk",
        ipv4_orport: "66.111.2.20:9001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "D405FCCF06ADEDF898DF2F29C9348DCB623031BA",
        ed_identity: "J5xSAf/GxrnzwL0sQcp36YlGybPxR4iBFQojImbNWKM",
        ipv4_orport: "5.45.111.149:443",
        ipv6_orport: Some("[2a03:4000:6:2388:df98:15f9:b34d:443]:443"),
    },
    FallbackDir {
        rsa_identity: "D5C33F3E203728EDF8361EA868B2939CCC43FAFB",
        ed_identity: "vt8/rq91Ra6acbRd4JbcZrg+SVzlsuhI+KepbBN+D2I",
        ipv4_orport: "12.235.151.200:9029",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "D7082DB97E7F0481CBF4B88CA5F5683399E196A3",
        ed_identity: "/9e91SgkjMz+w20YOF4hpG8Gz71H+BMAGaozyWh7gV4",
        ipv4_orport: "212.83.166.62:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "DB2682153AC0CCAECD2BD1E9EBE99C6815807A1E",
        ed_identity: "C5DCBbKmte43sA0EFfq5REk1UDwEyS9/96lCiF1Bnx0",
        ipv4_orport: "54.36.237.163:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "DD8BD7307017407FCC36F8D04A688F74A0774C02",
        ed_identity: "3YzQBY0tjBYayCeyPJVGtw3sG7D1YSxXI3Gn0QfJeFw",
        ipv4_orport: "171.25.193.20:443",
        ipv6_orport: Some("[2001:67c:289c::20]:443"),
    },
    FallbackDir {
        rsa_identity: "DDBB2A38252ADDA53E4492DDF982CA6CC6E10EC0",
        ed_identity: "2LuG4YFsqQ63Ym0IP8RfC59zhmuLtC8qN473KOIZkEQ",
        ipv4_orport: "83.212.99.68:443",
        ipv6_orport: Some("[2001:648:2ffc:1225:a800:bff:fe3d:67b5]:443"),
    },
    FallbackDir {
        rsa_identity: "E41B16F7DDF52EBB1DB4268AB2FE340B37AD8904",
        ed_identity: "WMgSFE01FsnHfrJocp3do08d7f6hcQKRduv6IR+QUFk",
        ipv4_orport: "166.70.207.2:9101",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "E51620B90DCB310138ED89EDEDD0A5C361AAE24E",
        ed_identity: "sklrzXlOB7IOPgrFhgK+bfXQiXwVaVCoIjWGOuoXWqg",
        ipv4_orport: "185.100.86.182:8080",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "E81EF60A73B3809F8964F73766B01BAA0A171E20",
        ed_identity: "ghHxTU+n3zfnrVtsAceD2el+1qAlkpJf8HjAOG1lB/8",
        ipv4_orport: "212.47.244.38:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "E8D114B3C78D8E6E7FEB1004650DD632C2143C9E",
        ed_identity: "e6DDs2vApNKxq0r2vIBmT6rL55Cl3iRtR0f99lgSkqo",
        ipv4_orport: "185.4.132.148:443",
        ipv6_orport: Some("[2a02:c500:2:f0::5492]:443"),
    },
    FallbackDir {
        rsa_identity: "E947C029087FA1C3499BEF5D4372947C51223D8F",
        ed_identity: "IAOuIm5ABXumGwC+iPWWSqlmLU9YaldnGL6tXcyE10A",
        ipv4_orport: "195.154.105.170:9001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "EBE718E1A49EE229071702964F8DB1F318075FF8",
        ed_identity: "CNiUuxHUn0xp1Gfjz+Bzy632Y5rj+W7KtaoEfDfVy58",
        ipv4_orport: "131.188.40.188:11180",
        ipv6_orport: Some("[2001:638:a000:4140::ffff:188]:11180"),
    },
    FallbackDir {
        rsa_identity: "ED2338CAC2711B3E331392E1ED2831219B794024",
        ed_identity: "ftz915sTd2+y7JnELlnDnC/jQWdw2iFb4hrykO5V/bM",
        ipv4_orport: "192.87.28.28:9001",
        ipv6_orport: Some("[2001:678:230:3028:192:87:28:28]:9001"),
    },
    FallbackDir {
        rsa_identity: "EFAE44728264982224445E96214C15F9075DEE1D",
        ed_identity: "s2w6QLaOQFL2tLQoHSS7+hrk42W8RmTK1Q4mp7uasn8",
        ipv4_orport: "178.20.55.16:443",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "EFEACD781604EB80FBC025EDEDEA2D523AEAAA2F",
        ed_identity: "W3yH/OWbKwWlaP9243SP30qJOf3/0tVvC1M4x8B9u+g",
        ipv4_orport: "217.182.75.181:9001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "F24F8BEA2779A79111F33F6832B062BED306B9CB",
        ed_identity: "v6YjNsq1tLsAUt+FlU2uv0Bpkn4iJ9UmkhYAcS3aBJk",
        ipv4_orport: "193.234.15.58:443",
        ipv6_orport: Some("[2a00:1c20:4089:1234:cdae:1b3e:cc38:3d45]:443"),
    },
    FallbackDir {
        rsa_identity: "F2DFE5FA1E4CF54F8E761A6D304B9B4EC69BDAE8",
        ed_identity: "ii5cAQdvLGAoaaP0SA2LPBSiqXl8HQNuGR7JeKsi9fU",
        ipv4_orport: "129.13.131.140:443",
        ipv6_orport: Some("[2a00:1398:5:f604:cafe:cafe:cafe:9001]:443"),
    },
    FallbackDir {
        rsa_identity: "F4263275CF54A6836EE7BD527B1328836A6F06E1",
        ed_identity: "F2A1yzDIBPuz2W+0RdLorUXzLjfdLIIf9a+cEH8uCuQ",
        ipv4_orport: "37.187.102.108:443",
        ipv6_orport: Some("[2001:41d0:a:266c::1]:443"),
    },
    FallbackDir {
        rsa_identity: "F4C0EDAA0BF0F7EC138746F8FEF1CE26C7860265",
        ed_identity: "hLfNwGAvN2i5N1ErZM5FqGlYlbxWWqNC5sf5t6ld5KY",
        ipv4_orport: "5.199.142.236:9001",
        ipv6_orport: None,
    },
    FallbackDir {
        rsa_identity: "F741E5124CB12700DA946B78C9B2DD175D6CD2A1",
        ed_identity: "iAYLZTzQ8qOBGnbJqBP52JqGWBdUfINS5YiskqOhLLo",
        ipv4_orport: "163.172.154.162:9001",
        ipv6_orport: Some("[2001:bc8:47a0:162a::1]:9001"),
    },
    FallbackDir {
        rsa_identity: "F8D27B163B9247B232A2EEE68DD8B698695C28DE",
        ed_identity: "ucdzkvv9kNWMbybz4CpMvdGUZPphjv9shfB3DuynaAU",
        ipv4_orport: "78.47.18.110:80",
        ipv6_orport: Some("[2a01:4f8:120:4023::110]:80"),
    },
    FallbackDir {
        rsa_identity: "F9246DEF2B653807236DA134F2AEAB103D58ABFE",
        ed_identity: "Nk1MWkriq/5vhqfDNBtiJWPTUOGxPi1Xj1ZJBCzSe4c",
        ipv4_orport: "91.143.88.62:443",
        ipv6_orport: Some("[2a02:180:6:1::3d8]:443"),
    },
    FallbackDir {
        rsa_identity: "FE296180018833AF03A8EACD5894A614623D3F76",
        ed_identity: "h+vpgiit/VapnknS1kv9pCqsJx7XX3WaWpRDKuezmAQ",
        ipv4_orport: "149.56.45.200:9001",
        ipv6_orport: Some("[2607:5300:201:3000::17d3]:9002"),
    },
    FallbackDir {
        rsa_identity: "FF9FC6D130FA26AE3AE8B23688691DC419F0F22E",
        ed_identity: "47HGw2yL2CRZHbg/22y8GzzQ70fy5sRQL+AfLH8l3XQ",
        ipv4_orport: "62.141.38.69:443",
        ipv6_orport: Some("[2001:4ba0:cafe:ac5::]:443"),
    },
    FallbackDir {
        rsa_identity: "FFA72BD683BC2FCF988356E6BEC1E490F313FB07",
        ed_identity: "1XEqrNow2olJOwX09N2/ixwregJsPECgqGAOvNMfL5U",
        ipv4_orport: "193.11.164.243:9001",
        ipv6_orport: Some("[2001:6b0:7:125::243]:9001"),
    },
];

#[cfg(test)]
mod test {
    use super::*;
    use crate::fallback::FallbackDir as Converted;
    use hex_literal::hex;
    use tor_linkspec::ChanTarget;

    #[test]
    fn convert() {
        let d = FallbackDir {
            rsa_identity: "FFA72BD683BC2FCF988356E6BEC1E490F313FB07",
            ed_identity: "1XEqrNow2olJOwX09N2/ixwregJsPECgqGAOvNMfL5U",
            ipv4_orport: "193.11.164.243:9001",
            ipv6_orport: Some("[2001:6b0:7:125::243]:9001"),
        };
        let fd: Converted = (&d).into();
        assert_eq!(
            fd.rsa_identity(),
            &RSAIdentity::from_bytes(&hex!("FFA72BD683BC2FCF988356E6BEC1E490F313FB07")).unwrap()
        );
        assert_eq!(
            fd.ed_identity(),
            &Ed25519Identity::from_bytes(&hex!(
                "d5712aacda30da89493b05f4f4ddbf8b1c2b7a026c3c40a0a8600ebcd31f2f95"
            ))
            .unwrap()
        );
        assert_eq!(fd.addrs().len(), 2);
        assert_eq!(fd.addrs()[0], "193.11.164.243:9001".parse().unwrap());
        assert_eq!(fd.addrs()[1], "[2001:6b0:7:125::243]:9001".parse().unwrap());
    }
}
