/* type=fallback */
/* version=4.0.0 */
/* timestamp=20210412000000 */
/* source=offer-list */
//
// Generated on: Mon, 12 Apr 2021 13:57:46 +0000

vec![
    // Nickname: Unnamed
    fallback(
        "BD5609383472735292627DB86D92A29F3CFEE52A",
        "YBP87LugFRTt8hGE1XmlvRt+ySYHU4hjbkSZWdstIIY",
        vec![
            "62.78.194.4:9001"
        ],
    ),
    // Nickname: frenchonion
    fallback(
        "52026565263963A4DA7C0A737E43850951405CDB",
        "CsMfFyqB1GJsKQG/j1ezYoEG5tF+IamVYc21R+G3tY0",
        vec![
            "51.91.121.255:9001"
        ],
    ),
    // Nickname: relayon0342
    fallback(
        "24352D30196BEFE5BB29A50923F79A2804527611",
        "8PIsBUhLCXY8FsyhPo/MLZzai1d1E+uEfAldSCKrlRc",
        vec![
            "185.220.101.198:10198",
            "[2a0b:f4c2:2::198]:10198"
        ],
    ),
    // Nickname: TORPEDO
    fallback(
        "45D67EDBFE0A61F9784F34A88DA6D5E13C397786",
        "3/p1Mwm26T1lDHOI35rHUwsWc/59iczoYiz9riJhWkc",
        vec![
            "77.250.227.202:7002"
        ],
    ),
    // Nickname: Islay
    fallback(
        "F4873B3EC3325B81DC36C7E38AD3A5ED12B2F339",
        "Kc4Gfn4pyl18Fy264BhfsDF2w9W873h/wlv0ZwrJy7k",
        vec![
            "37.187.23.232:80"
        ],
    ),
    // Nickname: relayon0233
    fallback(
        "4031460683AE9E0512D3620C2758D98758AC6C93",
        "6CVvtuAjb4Gln6qzO+koYthipfWjjGUTqlTQ7jfXLDM",
        vec![
            "185.220.101.144:30144",
            "[2a0b:f4c2:1::144]:20144"
        ],
    ),
    // Nickname: YagaTorRelay
    fallback(
        "BC7ACFAC04854C77167C7D66B7E471314ED8C410",
        "bB7qi9DiUYXTK41Vtnp4CF1miLtzLj8r0PKBzId4C78",
        vec![
            "116.203.140.74:9001",
            "[2a01:4f8:c0c:e646::1]:9001"
        ],
    ),
    // Nickname: AngelsOnTheBeach20
    fallback(
        "89649A64A8F167840977C1E13A50E9BB13CFD4A9",
        "Ypx8p4wL06qqhQkFVpHk5eCqkGeU0ckseIsDLLMVhjI",
        vec![
            "109.236.63.122:9001"
        ],
    ),
    // Nickname: TrickDepression
    fallback(
        "C6604D457AC319E53DC314B81F0EF9D16CB937A0",
        "hdp0QdYOzpAcN7Z59f3P1WsBqz6/c0vXCxdUmWgA9yY",
        vec![
            "8.209.79.125:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "18805962D990758381A3938191689045D287F0C5",
        "xRYbfxntj/6nHfG8KB4+ae9ADwN0cxreevfu7/0Z3/U",
        vec![
            "198.245.60.91:443"
        ],
    ),
    // Nickname: myNiceRelay
    fallback(
        "900777F6E1307328D5C39826356925FDECB0790B",
        "mbstBsgc9nktmnyXW1K/Ft9FifHI2K7llqZOE+EzzqA",
        vec![
            "62.171.180.6:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "FB5B345BFE0D48C26E3BD60A43419658467BAD5F",
        "krr77B2uUSHeEdCLkaYSwogEx1a5/IATSy77LclOIdI",
        vec![
            "85.209.158.115:443"
        ],
    ),
    // Nickname: trumpet
    fallback(
        "5889A54CCD68C319F6F8ACEFF81E063E6E84B9BE",
        "/aqPJZhqtfBtxvO0lWGUc0VIAm8x0p0sXntnLCuKegE",
        vec![
            "147.135.64.217:443"
        ],
    ),
    // Nickname: weizenbaum2
    fallback(
        "8A2D71CBCA33F13A3EA9614DE28AE3F669D84987",
        "9QwhH3glg61aSiVXDT2eecjOigZatKdfEVqO7KWpHug",
        vec![
            "62.102.148.68:53"
        ],
    ),
    // Nickname: DigiGesTor4e2
    fallback(
        "BF1B662D1DA4E55F700C130AC58574B47FB7EB8E",
        "eYK6bYjKNiFL3HV2mJpb/BHlKP4u4P4pX0lBYFuDcMk",
        vec![
            "195.176.3.19:8443",
            "[2001:620:20d0::19]:8443"
        ],
    ),
    // Nickname: cgps
    fallback(
        "EE58464CA9602C639C11CDF6615384B0BC121542",
        "XzMRvIMEDEjrJqLBQuLIfUV11ErZpeX9gRWJHKXhYsk",
        vec![
            "121.200.26.46:300"
        ],
    ),
    // Nickname: relayon0109
    fallback(
        "30E747B3058994CCCBEAF8B5B4791A9F1628AB7D",
        "jg23mbpyAhUz99WlFzJpgnePrE/qdpgJ/5yjCZW62Qo",
        vec![
            "185.220.101.1:30001",
            "[2a0b:f4c2::1]:20001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "AFC3B368F109742622662B7385501AC65CCE2685",
        "v25g+DplyumKImEMmWouHqKBe24nXl7ueyOuX0IPEBQ",
        vec![
            "198.245.49.18:443"
        ],
    ),
    // Nickname: marcuse1
    fallback(
        "EFAE44728264982224445E96214C15F9075DEE1D",
        "s2w6QLaOQFL2tLQoHSS7+hrk42W8RmTK1Q4mp7uasn8",
        vec![
            "178.20.55.16:443"
        ],
    ),
    // Nickname: PrepreUseless
    fallback(
        "60685893A57D66562A0754BEE3B6A6E68082C8BE",
        "XvSV52lmKRQYNwUcMNuIe/ZtiVLU4kmXf0E9ioDWVB0",
        vec![
            "47.254.134.152:9001"
        ],
    ),
    // Nickname: Jnthn
    fallback(
        "A397CF83A1E1D66EAC5F437E47B6882A2FB473E4",
        "Ih04/JLNlxqLxoWXIEpOXo1R+dSMlc9qtYcjtqr0F40",
        vec![
            "195.201.29.252:9001",
            "[2a01:4f8:c2c:b8bc::1]:9001"
        ],
    ),
    // Nickname: bagespottedtide
    fallback(
        "B49EAAE4690E5CE762D1DF8B00FDE05970880EAD",
        "7cmbPeJ1ol+Orb2CiESaQv0B2CJlLAOTQz4R2fP9fr0",
        vec![
            "103.253.41.98:9001"
        ],
    ),
    // Nickname: GrvityImmune
    fallback(
        "989D1D15EB4C28F11FC620B622FED221DFAF2BA6",
        "eApFoL8lJ25ft81dAk/qrJkFChqNuwWiG1pBQfjS5RY",
        vec![
            "47.56.94.99:9001"
        ],
    ),
    // Nickname: evilfactorylabs1
    fallback(
        "35C7266E4BA5EFAFE1032C24B657BBF14ADDD88B",
        "bT/i0AKFMxdsk9QEmjo3tFqoWjzuAPQc4+18iEvXzhs",
        vec![
            "192.46.225.58:9001"
        ],
    ),
    // Nickname: Boedi9Worldwide
    fallback(
        "55BEC1032A3C66AE5ABF26D11505352318736D45",
        "yxQFl/Dp3jTC8VBsAY1ejCA8gTziYiE4yfsI7UoyRU8",
        vec![
            "37.120.167.200:12312",
            "[2a03:4000:6:440c::3]:12312"
        ],
    ),
    // Nickname: peep
    fallback(
        "B7D773E2196DB5B4129D3C050C063DB0F8DF91A5",
        "0bRHFOLN+anQMKU6uiUe3M2BRVeYpk1vU1R2RqZY134",
        vec![
            "195.201.94.113:443",
            "[2a01:4f8:1c0c:6f8c::1]:443"
        ],
    ),
    // Nickname: Assange008fr
    fallback(
        "ADB98B27D7A3FB5732068FD23602A1BCB3BE9F38",
        "qvCRVASsfT9VoZ/igQFqnekhgr1LUQxN9ijWGKXQ06Q",
        vec![
            "62.210.105.46:9001"
        ],
    ),
    // Nickname: VolkerKeyWebExit
    fallback(
        "C9DF64AF926E2E584E345D13BCE4A97C231A36BE",
        "r2poLUyFSamzl67ZFNVm3ap1LKbQSprn7syXbTq8GEM",
        vec![
            "87.118.96.154:9001"
        ],
    ),
    // Nickname: murphtor
    fallback(
        "CE77F6A537FD1ECCCDFF0FE8E5FB446A438E3754",
        "PPiV2j/EOK6Um4IeVYswpeB47EDBnVOvfB8JgFGXuyM",
        vec![
            "185.251.165.74:9001"
        ],
    ),
    // Nickname: somsom
    fallback(
        "E5D13B726489E91A260F70B95B7AD9949BB6A95F",
        "dBlhuoCCLSvzmYXKthzRX6AD17fqOw8lk2AUA779GWE",
        vec![
            "188.195.109.45:9001"
        ],
    ),
    // Nickname: Joker
    fallback(
        "DEF3365F1C012F80E56877B5EF05CE72BDEB0CCC",
        "6SwTrfuwD93ydPE3yLhNaP2SDaQjmt8UOTcg+SH9Le0",
        vec![
            "139.162.210.252:443"
        ],
    ),
    // Nickname: Assange034us
    fallback(
        "55B5A9DB9C2B57C035437A3CC52A6B11D877CBDD",
        "v3TzfgLYR6ouoFyl9E4bvU+EhPrswUqSC50AzLGaI7c",
        vec![
            "162.212.158.82:9001"
        ],
    ),
    // Nickname: piersic
    fallback(
        "B7EF647EF659726C716243A82877D20AA7978EBC",
        "fDIBf58srtfOlp+zO4DksnVSMbj7+jBoWuBzjjEVUyQ",
        vec![
            "185.227.82.7:443"
        ],
    ),
    // Nickname: ContaboNixGut
    fallback(
        "BA671B70E696AB2F85ACA3D998B8008D14556715",
        "hCRCsg1OOYA3pqtF2pl2ol5a8W1iEnwcl0AGczRjgLs",
        vec![
            "5.2.78.69:9001",
            "[2a04:52c0:101:358::2bd7]:9001"
        ],
    ),
    // Nickname: ntrltor
    fallback(
        "78B7753E2C5B683BA7D9A778563FFEDEDE1BE75F",
        "VgYjhqwLY5MUS1p5cZ2+tccf4JUgGpD6HWcIefnMNeM",
        vec![
            "143.107.229.210:42256"
        ],
    ),
    // Nickname: frell2
    fallback(
        "B638FBC032174CAA9409B83B5CEFFB4906D43434",
        "yVh1ayTLWTYnCYogrziwVGyRGgbLH3Gx4VhgTWyuJcw",
        vec![
            "85.10.240.250:443"
        ],
    ),
    // Nickname: affectiosocietatis
    fallback(
        "5C9A66F40A63D9C8DF9700E6DF9E1FD47D8AD317",
        "AHzezq7zyD9fpMQRKUOCAhsqcXWFJuvvoJAE11YkNH4",
        vec![
            "91.121.160.6:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "BD1511AAD7FB7686636DEBE43D4024E5E56C6C98",
        "zxBaNvOSxq3IJ9XAKmSmeOBgHltfef49SpmimDgad6I",
        vec![
            "104.149.129.210:443"
        ],
    ),
    // Nickname: angelinajolie
    fallback(
        "6B9EA8927AB6E94E216067E65372182343A5AFA2",
        "ewKGIbk6IfFRJvU6Ms7/pD/9C50RkRxNumBDByzi9es",
        vec![
            "62.210.83.207:8080"
        ],
    ),
    // Nickname: relayon0201
    fallback(
        "4AD0B40B0FC679CC300F398BCEBE9D000833F62C",
        "nusvUCN+7u6q1Lv9VA2z2CIib3v8ihQjQVb2JGK9CN8",
        vec![
            "185.220.101.145:10145",
            "[2a0b:f4c2:1::145]:10145"
        ],
    ),
    // Nickname: relayon0225
    fallback(
        "E013CC98CCC1E6AFDCFC9681A53DC2DEFE5D4CCC",
        "Y6dK/jWVlTPtfiwVp1Y3eBqct5cHPIcNdKBK//Db274",
        vec![
            "185.220.101.143:10143",
            "[2a0b:f4c2:1::143]:10143"
        ],
    ),
    // Nickname: uzieka
    fallback(
        "54DE63F4587058B79152A75A0238D7F7A0279215",
        "U88bW9b15bbm0XaYR+uDSbffTH5aGNPH5P71srtjLmc",
        vec![
            "192.36.38.33:443"
        ],
    ),
    // Nickname: Unzane
    fallback(
        "2C4E15CD40EE3D2D6F062F04ADFE9B85C8C3C52B",
        "lkh/Nq9LHZwHMpqMN6n5zolEr5NkCMeQ9zbYRIX8u/w",
        vec![
            "184.105.220.24:9001",
            "[2604:b480:fff0:6::2]:9001"
        ],
    ),
    // Nickname: relayon0113
    fallback(
        "9910C6DEEA9907EE7AEFCE0DA072F94F86EBFD48",
        "eeb4N/LT5Xfa3ZQq7YIA7cfe34BnXLQq2o59ZtsWCIE",
        vec![
            "185.220.101.23:30023",
            "[2a0b:f4c2::23]:20023"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "32BFE1401EFD886ADAD89E369D09D8C8451B8872",
        "s6F3W9fYEd8DJuzfcor3Ini0p/45s1tscVy8w7HWpvk",
        vec![
            "85.209.157.3:443"
        ],
    ),
    // Nickname: shhovh
    fallback(
        "39F096961ED2576975C866D450373A9913AFDC92",
        "8fN2IHdgryRlXZbRLcvvBhMaYDRo8zCAIE0d/C+wOpU",
        vec![
            "198.50.191.95:443"
        ],
    ),
    // Nickname: tommyboy
    fallback(
        "10805A3833774B812D07EB7D1D75A54021590F56",
        "dhLGlF6Lo/7YZ9eMRLWks6tCBTG9ylJgNUk+sWDfuyY",
        vec![
            "116.12.180.237:7443"
        ],
    ),
    // Nickname: niftydemogorgon
    fallback(
        "F21760E63FE2BB45629BB14FCDB0FD677485DAF8",
        "bi3cmUHdwlkMqU4aWnASDF5NsQZfvZ4OLvWN4DMQhe8",
        vec![
            "185.220.100.246:9000",
            "[2a0b:f4c0:16c:10::1]:9000"
        ],
    ),
    // Nickname: ntfshard
    fallback(
        "771E0824EF82D85E04D80116554111E37F7EB796",
        "k4eOhddautX0Invj6DIZOJWRZk1RJ/UJh7UXdE32HNs",
        vec![
            "109.71.204.203:9001"
        ],
    ),
    // Nickname: grenouille
    fallback(
        "DD823AFB415380A802DCAEB9461AE637604107FB",
        "0lRoDJwLTvs0kiowyJrCyECiL5QnYg5QktEZi/uXIfI",
        vec![
            "178.33.183.251:443",
            "[2001:41d0:2:a683::251]:443"
        ],
    ),
    // Nickname: Reyna
    fallback(
        "D95BB7E25EC4F64E499088DE5BFD9B6E61EC6ED1",
        "++UOe7WALsaIGljVlwyP4Tw6vlsLSxMuu20lmXGyaHY",
        vec![
            "154.59.112.72:443"
        ],
    ),
    // Nickname: artischocke
    fallback(
        "61C03827FD9914CDCB2EA809A824A435AEA0189A",
        "wARQnal+Im1kc0nw2XQK62x8kfQ+7OoMXaaKBNBh8SY",
        vec![
            "109.70.100.29:443",
            "[2a03:e600:100::29]:443"
        ],
    ),
    // Nickname: nicknametor
    fallback(
        "AD1FC4AE877B2FFEB3C84F1A6B76E9B057AAEF4E",
        "QnDexV/BDRPTxXUmZdS7S8Yj+08S+OjsdOKMoaq/6IQ",
        vec![
            "88.198.112.25:9001",
            "[2a01:4f8:c0c:53fc::1]:9050"
        ],
    ),
    // Nickname: AlGrothendieck
    fallback(
        "8E6EDA78D8E3ABA88D877C3E37D6D4F0938C7B9F",
        "+cA5po9F08p5F+FsyKqfruH80jejDstEQ0sH7CWvBkM",
        vec![
            "80.67.172.162:443",
            "[2001:910:1400:107::2]:443"
        ],
    ),
    // Nickname: Phoenix
    fallback(
        "270EECB837AD914C01ACC777152AEEB1EBCDBDE5",
        "2T82j2V9O9h9iNTyT1ySCHplBP8nJJNw/RT3mP+ejxY",
        vec![
            "104.149.139.42:8080"
        ],
    ),
    // Nickname: niftygrolantor
    fallback(
        "B891CB6370CF7C51C6FB24D80947AFB7ED463D00",
        "cJmkc0RHHSURV1mo73Ao6Rx0M8Yq3cw/Vx83HF/q0O4",
        vec![
            "185.220.100.247:9100",
            "[2a0b:f4c0:16c:9::1]:9100"
        ],
    ),
    // Nickname: geekboxNEO
    fallback(
        "81893D8444F0C9100CCD963BD0D62BBC50121D14",
        "E6qtfuSuKygOX9A8nE5aOGM6t2+3MTSA64R3hU1nrco",
        vec![
            "95.216.118.16:4223"
        ],
    ),
    // Nickname: maplefire
    fallback(
        "98A6022D39DD25902D7728B65BE28E5557F5B914",
        "PHhyXvH0B1ymPtrzLVL5KetSq69273AcfVm2RmMbAWY",
        vec![
            "116.12.180.234:9443"
        ],
    ),
    // Nickname: PancakeWhore
    fallback(
        "F00EC2E0A2CA79A57FE7A0918A087987747D772D",
        "9pRT8vy/kCgsPq4VglNvQWoMevhMkUIsuUlEDri4ObI",
        vec![
            "94.154.159.96:9001",
            "[2a0b:f300:406::]:9001"
        ],
    ),
    // Nickname: mac68tm
    fallback(
        "155513DAF42E18FA16FCE77D08417E460785A95B",
        "n0zpz24Lsy0Nh0aY6ujtFW9g9fIoCi/UV/0AXNmw+XE",
        vec![
            "31.127.34.9:9001"
        ],
    ),
    // Nickname: damita
    fallback(
        "A9F7185499C5784E35B5C25744ED4AB75437CE5D",
        "9caQ0TZ9yYLs4VkhBSBdqtXNwixni7PIpiM0S1TnuZY",
        vec![
            "91.229.76.124:443"
        ],
    ),
    // Nickname: ChristopheRelay
    fallback(
        "50BAD4E48646797796107ECF0192178495247202",
        "bxZI8bS/jD9ecau1JuF4gX9qCgxfR2cRcJyOvL1zK1I",
        vec![
            "192.0.128.86:9001"
        ],
    ),
    // Nickname: Hydra5
    fallback(
        "3C90CA5857705D7C6C176D475C592AF2789FDDA7",
        "iP7tvPfcbhsWC1qaw023HtZx4sKuhuW9b7K64AJYN68",
        vec![
            "107.189.31.181:9001"
        ],
    ),
    // Nickname: BorrisvCorbyn
    fallback(
        "29A39144AD141242436D07901F7A8B91F7516A66",
        "Cib4ahxcH5IcrEgnAvG4Y0K8aQ6OMAgyA5nbAVs5/qE",
        vec![
            "176.31.116.155:8443"
        ],
    ),
    // Nickname: mhgngq5364v9ny85y
    fallback(
        "656C60B5FC9810BECA159B9BFF0AB999883ADF02",
        "NvEC1Aj/lRHbaFpwwK8wE0I5oCySsG40TKMR63YkB4o",
        vec![
            "91.121.181.6:9001"
        ],
    ),
    // Nickname: Warth
    fallback(
        "BB1B414127F0B28C8024380E59E7454AADBA207A",
        "NTQiqjQgkX+UHZ62WfXiX2vIXviyIdfloQn3rVGAkpE",
        vec![
            "45.153.160.131:9001",
            "[2a0f:9100:110:a::83]:9001"
        ],
    ),
    // Nickname: tubealloys
    fallback(
        "4B582F3F4BB4DE56D7728DEB22AA255350870F98",
        "LpOt9BLCrYbw599gg5KgmIestknC3iTp43Z3NaIlAOQ",
        vec![
            "213.144.142.24:9001",
            "[2001:1620:ad1::24]:9001"
        ],
    ),
    // Nickname: metaverse01
    fallback(
        "FA5F1AB3468F808B2FB05F2155C0481A3532C787",
        "Rw7YFQCx0cM9ZASP5B1IyIv4exORwcKSddoyoL99WwY",
        vec![
            "185.97.32.34:9001",
            "[2a00:66c0:1:1::34]:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "229B87191C69AE03FC16151C3BF019B0FEC2DD8F",
        "5ho5DoWIiCXdF0SmDDp6o7Tr4nbQUxst5hgu2RY5FBk",
        vec![
            "185.90.61.218:443"
        ],
    ),
    // Nickname: marcuse2
    fallback(
        "C656B41AEFB40A141967EBF49D6E69603C9B4A11",
        "+tt2zAB+flZdk/xAhZMZ//7WUKDmWT6ZQPrmcDsfcN8",
        vec![
            "178.20.55.18:443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "51800AF38B30ED1454DD74CB412BADCED5F60593",
        "glUiM/UpKFEJRf/eM3wFpIMY/BCz2hPe8fzHc34glZs",
        vec![
            "37.191.206.197:8443"
        ],
    ),
    // Nickname: QuintexAirVPN4
    fallback(
        "CC4A3AE960E3617F49BF9887B79186C14CBA6813",
        "J6Asug5XroX7A3hVDBCRjKLG7XQ4T46r7QDFAmWYfRM",
        vec![
            "199.249.230.115:443",
            "[2620:7:6001::115]:80"
        ],
    ),
    // Nickname: PXArelay03
    fallback(
        "B6D4916A98D99027DA25D42D70D686F0B3663F35",
        "FACCiUfcccrBvVzkZRGEp6qDXuRMhtraVsiv8R60Rh4",
        vec![
            "185.233.252.14:9001"
        ],
    ),
    // Nickname: forTheLoveOfHotDogs
    fallback(
        "5A224EFAC453F7EF2D0435E336890DECDC5CEBFD",
        "yXXNzS1qsaKe+b3DxxSrKISKxwKriV88wz15wIRSLb0",
        vec![
            "46.105.227.109:443"
        ],
    ),
    // Nickname: lurksquad
    fallback(
        "3EF75DDA77A5A0CFD58DC027BF7B1251D97CD084",
        "3AcRKqv405gCu7gbG9qmFqC2j/Nmwq4MxYr2kp13I7k",
        vec![
            "46.72.207.35:639"
        ],
    ),
    // Nickname: TorDotTeitelNet
    fallback(
        "76959901386E8C908F50235D9894007886B67C2E",
        "4hz5I4cuZUC7NuSgix0srExSSHjgoleSzUtTOH9YJV0",
        vec![
            "198.98.51.189:9001",
            "[2605:6400:10:58f:8768:8283:1a62:bdc6]:9001"
        ],
    ),
    // Nickname: 420isGay
    fallback(
        "47FA3C32C5C0A8D0CEAD5F4315C50054AB34170A",
        "k5/93Kvx2d4wLIPhM0e2N/iDQ3Mhnct0EaAkNG4xRoo",
        vec![
            "217.160.255.217:443"
        ],
    ),
    // Nickname: 2HG
    fallback(
        "33DBA330433E2915BD0EE66787A48863C818C0BB",
        "qLciD8drDgPYHhyH4RlhqKWqoNXr4D0zpIrCaQYe4HI",
        vec![
            "163.172.68.222:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "825AD5D33B2A5C41BC647047D6B63AC41C4C5021",
        "Q7iaLulO2Aej8iAgmxsO1zMftK+fXTLsiddhOUehdtc",
        vec![
            "78.94.253.253:9001"
        ],
    ),
    // Nickname: torrelay0001
    fallback(
        "CB040846C647F338EE1950C6CC03267102088C50",
        "SH2TmE9rduVRGwFzWZEIyKF6cZyjCioI/PDBBGqL/cg",
        vec![
            "153.126.128.94:9001"
        ],
    ),
    // Nickname: relayon0337
    fallback(
        "30DBF7A773F4EE3BF6D1B7407DAECF40220AC8CD",
        "N9ZcPhFdyXFFluO5os4tr1w6oBrhXd8/JWh4yx9dAek",
        vec![
            "185.220.101.205:10205",
            "[2a0b:f4c2:2::205]:10205"
        ],
    ),
    // Nickname: kukuruz
    fallback(
        "D24D0C28AB48768CF8B79DD762D61DB4FD015677",
        "CaWQj48yrPcbtSRLbH8hoIWYCm3lfsTqoJwbZ9txE1w",
        vec![
            "109.70.100.14:443",
            "[2a03:e600:100::14]:443"
        ],
    ),
    // Nickname: Akka
    fallback(
        "56927E61B51E6F363FB55498150A6DDFCF7077F2",
        "CVTjf1oeaL616hH+1+UvYZ8OgkwF3z7UMITvJzm5r7A",
        vec![
            "95.216.33.58:443",
            "[2a01:4f9:2a:2145::2]:443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "A64BD6DA33D870F3807C5775DEA23F6EE32289B3",
        "indNVFzp2Mxj2YI7+uomV97H2UBYs3LrbPs/6xgSBrI",
        vec![
            "95.216.154.139:9001"
        ],
    ),
    // Nickname: Geoff2
    fallback(
        "E767C3B8295AD79B02E80A21345C9F2B3C2AD7DB",
        "ODq4aRYPjngeL2HEpeovgFa4663O1ElJE5PfCT+xqKs",
        vec![
            "178.254.31.125:443"
        ],
    ),
    // Nickname: interfesse1
    fallback(
        "F6D600CF13B3BBE2A91A0653F1EC9D00E7CB3A6B",
        "mRkVDTSlP/rwdbuOWd4SkS8a+ra6iXg4mpeQcbkDILY",
        vec![
            "85.195.208.154:9001",
            "[2a02:168:c603:b01::42]:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "011668FE8270453DA534E068A5A7763A190B3F4E",
        "xNiMo52LpbjVZ3OqW2MiWDf+unE685SMIWIwMdBldl8",
        vec![
            "38.145.200.61:443"
        ],
    ),
    // Nickname: ca0akatala
    fallback(
        "D111CA928084A907D8BE9B3F1E1D05227A5FBBE0",
        "6eRiAsGIbHwlNGQPedWaZvqcbLOa9nbSGQ9oSqCgSiI",
        vec![
            "167.114.144.152:9002",
            "[2607:5300:201:3100::397a]:9002"
        ],
    ),
    // Nickname: Route66
    fallback(
        "0CE3B73DDFF92FF6653A9C7F9003A32BB6C2364D",
        "aVCGw2my9KgQUnobesjkAK9+0gnotbdCIST0U3RZ6k8",
        vec![
            "88.88.79.90:80"
        ],
    ),
    // Nickname: t0rnod3
    fallback(
        "5582BBEC12380E34D7DFB8C237939A0B317B205E",
        "WPAzGuNSd4A6+ukH95/PTerBUDmGlc7CvBP4D7TPLoU",
        vec![
            "149.34.27.137:9001",
            "[2001:470:1f13:ab7::21]:9001"
        ],
    ),
    // Nickname: BeFreeInterwebs
    fallback(
        "231D0461EF09007C43AAE5E523964187055E2A30",
        "U/BkCJ8Ef3+GsI+bQ34pm8T5547E+Nqf/NoqhPoS/K4",
        vec![
            "198.98.52.143:9001",
            "[2605:6400:10:173:7210:1108:1119:7111]:9001"
        ],
    ),
    // Nickname: Enos
    fallback(
        "8EB722FA1AE9DDE1914BC21FEA22819D4DE99DB4",
        "xt+EQ6LOExJfMdGHviDxx6ZAmT8hyJv9sIUrtFtXPRc",
        vec![
            "195.189.96.148:443"
        ],
    ),
    // Nickname: pros2
    fallback(
        "C1BB67D3FBED68D4BAD400D1A49C5B79ECE3965E",
        "QdjnK1pJkLcoKS+ydS03X6DVO1m8GfkpjbDVE5ZtEGk",
        vec![
            "145.239.84.172:80"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "4B6D72A7D9A966A4856BFB01DCCA1940943EF023",
        "CAUt8zTRwIcx0xtoCqIpGRKdcWKuZjxLNkzBeR2u4ZU",
        vec![
            "144.76.170.20:443"
        ],
    ),
    // Nickname: Assange018us
    fallback(
        "BF7168623AD4FF542A9E940C4CCF575D9BE16323",
        "7FNXNQXT0jyoqYFoHe3Ca45IzYeFDa7+J+yIekZVAxE",
        vec![
            "193.160.32.19:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "FFB605C86D606991ADED7842269FA25A03B4A4D0",
        "h4S8mdHKoHXN8AP0FhwEem8KLgx8FCuw0LmGr/tZ4ps",
        vec![
            "165.227.174.150:9001"
        ],
    ),
    // Nickname: imANiceRelay
    fallback(
        "C0A0FEB6473F3F31822BB8F008049718CA017627",
        "HAR5OmrqLBEH1ZsnyqltSUo1LHst1h9Gn3B0rekqclo",
        vec![
            "37.139.22.180:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "AB10D5040BCBBA912FA448B8CF2A653DC8ACDC2C",
        "nVGTIUkNWXIPVBtsjgDnKuCmS18RpLghkReNk98ALnY",
        vec![
            "51.158.147.25:443"
        ],
    ),
    // Nickname: SpongeBob
    fallback(
        "1C0D0AF3FF05CCBBA4B6ED262196A4C5A76102E6",
        "7+ww9nAnXMLkZMGYhxpxhjPS1CK+MTcVvYw6QOn+r0A",
        vec![
            "104.244.76.13:443"
        ],
    ),
    // Nickname: trustn00ne
    fallback(
        "F5E1B96BFE700FF8BF09DE5A02181EBB48E218F7",
        "VqvSSywtwLR1lqYU2VGW0nPZy7dXqHB7eO6NDq28WDU",
        vec![
            "87.248.7.41:9003"
        ],
    ),
    // Nickname: FalkensteinTor02
    fallback(
        "0512FE6BE9CCA0ED133152E64010B2FBA141EB10",
        "E5QPti6y4w8KJY1W24A5m7nUjyPGXMYi0dKg2iAbJSw",
        vec![
            "5.9.43.211:9001",
            "[2a01:4f8:161:32c7::2]:9001"
        ],
    ),
    // Nickname: JanewayMurdrdTuvix
    fallback(
        "B0335F7872A698A86E5E9AC3CF323B50AEF9C081",
        "9CR24JVaDrDTAgrjK5BqrHCSxZS0Fdt8FTp1UGpV9g4",
        vec![
            "185.244.192.247:9001",
            "[2a03:4000:27:102::]:9001"
        ],
    ),
    // Nickname: ididntedittheconfig
    fallback(
        "B0F17A56FA8686CCB33D3F302FC40F06F463B4AE",
        "MEYQa/ca5CTIOwTB7AxpA9cM6K7unsH+EV9ocT09Bi8",
        vec![
            "142.93.169.197:9001"
        ],
    ),
    // Nickname: CalyxInstitute14
    fallback(
        "0011BD2485AD45D984EC4159C88FC066E5E3300E",
        "/AcSvVFxaIBxaB5I/7mwdVbMdP6JjDsEPVLU6Hj22a0",
        vec![
            "162.247.74.201:443"
        ],
    ),
    // Nickname: Playstar
    fallback(
        "5975858B6A1F37CCC96026B946EACF08E1772D0E",
        "8cCNlqECZvDx9GtXLr+qoBCrl55Eg6L+1cHWLD2+i4A",
        vec![
            "192.121.44.26:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "03D2E0B37A0F07408FD87F69E4A9928DEDE3405B",
        "gY6ihy84XOAJ18sMbKKUBt/JmSp7a+kQikYeXBY1f6I",
        vec![
            "78.46.174.72:9001",
            "[2a01:4f8:190:5364::2]:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "835FFE642EFA3BB7936663D2365A15D319FB6226",
        "6fjgqQlNAZV9UN66txciYXAN8s23cFCfAli35raz738",
        vec![
            "109.87.25.148:443"
        ],
    ),
    // Nickname: MasterOfDisaster
    fallback(
        "120F89D102F96647D2258166B3BB50CBFCEF20E3",
        "w9ZTcLNRYEluzjj5NS6lqnH1uhwTGIqX4Cvq6X4dNts",
        vec![
            "167.86.94.107:9001"
        ],
    ),
    // Nickname: OROGOM
    fallback(
        "D0D93D5E8B46BD72B68617B402E2DBC16F8AA040",
        "CF+v6NSS5jqXlTyFUY+3zt6PC2Q1DI4TBOhN+71/xzY",
        vec![
            "50.7.8.141:443",
            "[2001:49f0:2920::d]:443"
        ],
    ),
    // Nickname: niftydiinkarazan
    fallback(
        "5628495D9939A8C139DD441402DE42F7012B7092",
        "3giNc3Xsb2TXTWhIiP35X5C45RDwPGVvHcn/dGkZkSs",
        vec![
            "185.220.100.248:9000",
            "[2a0b:f4c0:16c:8::1]:9000"
        ],
    ),
    // Nickname: mitsuha
    fallback(
        "C0DAAAE5EE461BBE13945FE4B52F32ABDC6BC376",
        "MuaxcQ7uCMXw7A1Tf4YYQSRLK34+jj71dVNkFX272n8",
        vec![
            "51.15.246.170:443",
            "[2001:bc8:47b0:1756::1]:443"
        ],
    ),
    // Nickname: portnoy
    fallback(
        "0A0C01DD0044E70318D9E3DA5F125A09069C57C1",
        "nnP04ZmcGO3tKNycHcAMoHRK/qLaw35nmTPhFr3w49g",
        vec![
            "185.198.26.149:9001",
            "[2a04:bdc7:100:16::ab2d]:9001"
        ],
    ),
    // Nickname: ThereIsNoCloud
    fallback(
        "C51701910DEA998F4F51287A71B7E94449A3E9BC",
        "WjVK/41QD92Q+4o9tTWPinYnfuKIYhhtGFjl5aCGBzw",
        vec![
            "194.140.117.58:993"
        ],
    ),
    // Nickname: LaMarreTAO
    fallback(
        "6B263B45B33B8E2C73AB80F9B0D73538B44BD75D",
        "A3Ug7j5ioU8N3DFZkttbC6WSbiHL5F3VzmetxDP7Bgo",
        vec![
            "178.17.170.13:9001"
        ],
    ),
    // Nickname: Quetzalcoatl
    fallback(
        "5BDD0633E0AC09763E49641DCD1BA3AB3A21AA83",
        "HjGp5vQQwfR424gG0FXNDbtqb5hiKnWiIJPnV9oA58k",
        vec![
            "205.185.127.35:9100",
            "[2605:6400:20:e87:d7d8:55b9:9c82:571e]:9100"
        ],
    ),
    // Nickname: nacor
    fallback(
        "98FB767DAD3438B187F5BC8968EC8BB57896032A",
        "7SFdRZjJkD+fTxUdJ+0hvHgIoEIiO7vO3Q0frvPdZJs",
        vec![
            "185.65.205.10:443"
        ],
    ),
    // Nickname: dorrisdeebrown
    fallback(
        "FDAED15C98CFE7A416E5676F614254F78406105C",
        "PH0b+c4R2nfMgXNmqJnCsiIH/qjyR0HrkFMVl/TsU/k",
        vec![
            "185.220.102.4:80",
            "[2a0b:f4c1::4]:80"
        ],
    ),
    // Nickname: rinderwahnRelay3L
    fallback(
        "FF9FC6D130FA26AE3AE8B23688691DC419F0F22E",
        "47HGw2yL2CRZHbg/22y8GzzQ70fy5sRQL+AfLH8l3XQ",
        vec![
            "62.141.38.69:443",
            "[2001:4ba0:cafe:ac5::]:443"
        ],
    ),
    // Nickname: theqube
    fallback(
        "E3B0739EEFFF0DE4203BBE8563F2A1C89D410347",
        "fQ84/psTPGKKzfzutcLxBzzKnB+Uvz6xgXpkR7g1LNI",
        vec![
            "45.125.65.112:9001"
        ],
    ),
    // Nickname: PiratPartiet
    fallback(
        "F27B47CED45724CBCE3B42926DD52F2091F395AC",
        "akRh78Lkl9LvqrRx9Mmw+hljSCE39szP8+iG/IggCqA",
        vec![
            "45.15.16.116:9001"
        ],
    ),
    // Nickname: pangea05
    fallback(
        "E9919FE0E3140D512A159DD2936924EF32053A40",
        "1O+l8onkpgxZ+LTDt+8QG15aVnpg2uc0WAi8So38i7g",
        vec![
            "37.157.253.35:443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "80A24E9A45687D64651ADF8EFCCD14052B593A25",
        "vWffzot6mRmBdF1k7BIBfKBLIsEhUvGgbDh7MHeRaH0",
        vec![
            "62.216.85.110:34049"
        ],
    ),
    // Nickname: Aloha
    fallback(
        "F9674F45A25CAA977E7B872807E0A070C121F5FA",
        "jADszf2kqKCKM1SOzUlFiLB8lo+H5Td6xsnSSFlJFfI",
        vec![
            "95.211.136.23:443"
        ],
    ),
    // Nickname: Assange038bg
    fallback(
        "9665A1A6EB9B98C57E446A483E75E05F0539B41B",
        "pNfdAB3BpCmIvn8wdZpmwr5qavHCR5F4de1ukW5mlo0",
        vec![
            "185.82.217.49:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "A29536C09FFA651336CEF34E8C5B7F1F81E5A7CC",
        "kLx3ZSAlkvGkPnt3pwNIde0yZ+lkPIeKyfikW7X0t5o",
        vec![
            "163.172.29.34:443"
        ],
    ),
    // Nickname: OatMeal99
    fallback(
        "70090E9F85FBE004EEBF58461FD6EDD5BF8A523E",
        "Hq3gIIUVKkIHw2qoXEbHTUgtdzEA+V4E/MdNHzUShQI",
        vec![
            "80.66.135.13:9001"
        ],
    ),
    // Nickname: wuglu
    fallback(
        "22AC139C979C0509154D18E033491AD40524AF91",
        "Ni6ZN8UrrQ51fF7AVcCdsC2HAs6fKXnNPUlYvQrhJNE",
        vec![
            "5.59.227.51:9001"
        ],
    ),
    // Nickname: Alastor
    fallback(
        "2EB3C230180694A1E848001E20F36F76A2287039",
        "r0Iw5c4GlYu/um4mwPaKFDVWSO1yQyM/daff7yzKgAY",
        vec![
            "62.210.123.24:443",
            "[2001:bc8:30c6:100::dead]:443"
        ],
    ),
    // Nickname: dezember
    fallback(
        "FD79B7F9230858B48E75F389661840C702511078",
        "HmWdGC3dz1comssi8oFbKaJIgjQLlTj0wiQCAnv+0fE",
        vec![
            "194.55.13.50:9001",
            "[2a03:4000:31:141::1337]:9001"
        ],
    ),
    // Nickname: MyCoolNick
    fallback(
        "AA98AE4BDB6E03BAA48011CAE828ECEC50B029C8",
        "L/VhskDywSDpLrW8FaVKdSeoOmnyCqKA3B+DOLwYMws",
        vec![
            "149.56.98.216:9001"
        ],
    ),
    // Nickname: sethsBSDrelayZ8350
    fallback(
        "6B805718A97BF653CB5546080BE756505F9BD65F",
        "ZWnqeQtQ1JrtshN7caq/m5Mi9mD0yRteW12+s31ROfU",
        vec![
            "151.197.240.154:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "469305AE56D9F446468E8BE8780219EED54EEF25",
        "cx4yb3531OwRpCVxStu9VP9+2k8r3Yi5pUtfA92i83Y",
        vec![
            "54.36.112.239:9001"
        ],
    ),
    // Nickname: sunburst
    fallback(
        "39A551CD188151147DC4D19523D06A09B5287C29",
        "SSyfCc0W9pP9FrOMo2i2MLPyN3mUEh1by4+YqoEIHP8",
        vec![
            "24.150.204.225:9003"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "B5C6F712D656C9390056AA9BA7020C87EEE9FA30",
        "Eu+pIMXg/vNQS4jvE0IV11L3za0jV/hrxx5R1fZJChA",
        vec![
            "178.17.174.10:443",
            "[2a00:1dc0:cafe::d6a2:ae67]:443"
        ],
    ),
    // Nickname: TorOrDie4privacyNET
    fallback(
        "A751D8BEE222564B7BA657F74B6658836FF1AEEA",
        "r44yv4YzqJFUEfGdfLSGLhvesFwPolCkfYJBY9FIFLE",
        vec![
            "93.186.202.32:9001",
            "[2001:4ba0:ffff:11a::2]:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "2736CFC07D1FA472FD42518A46BC720A62E85C38",
        "i3K4RdOfplgvA3K60Yr/IHN4pjRF/NERGhVHF3J7l+Y",
        vec![
            "195.154.106.60:443"
        ],
    ),
    // Nickname: MaiaAlston
    fallback(
        "7EF6E998564211FB86881FEA2627AA9119BD9842",
        "F0oaccmCdnlowwGZsBTs0i5flavi5uCpUSnRp+c0ECE",
        vec![
            "31.13.195.248:443"
        ],
    ),
    // Nickname: Zimmer22020
    fallback(
        "36A5C502C31729F26BDC923E4B5F9501B0A20B79",
        "JzHke50pkPWm/+1FUraHK+hngGUefiC6w4AHwJs0oXI",
        vec![
            "176.123.3.222:9001",
            "[2001:678:6d4:5010::a13a:101]:9001"
        ],
    ),
    // Nickname: Vinnysrelay
    fallback(
        "D21267A1EDC1863DA452A1BFDC6021197A0F8983",
        "7jIrHP7xMLwJZEGPpPQ981UNT2SoydNLv5LPfPYF0os",
        vec![
            "51.195.124.251:9001",
            "[2001:41d0:700:43e4:d950:f9e7:ae78:1]:9001"
        ],
    ),
    // Nickname: dorinne
    fallback(
        "04EE5E1B23127D26A36F71C66810D88B0B80BB91",
        "qkKQSm63z8ciFpY57z+VwXHN3R+etZwNfUd2CCM2/fY",
        vec![
            "91.213.233.138:443"
        ],
    ),
    // Nickname: Quintex85
    fallback(
        "00EB3A12C77E70F19F66A7BBD094D62969AF350D",
        "9pTjuZ/qwd9Mch+k0t4UyOq6NyFC4TSfGnqDPh2YaC4",
        vec![
            "199.249.230.174:443",
            "[2620:7:6001::174]:80"
        ],
    ),
    // Nickname: Hermes
    fallback(
        "09F64E00F34C88F604163F24D37BEAF9245702EA",
        "GWzaybg6vzcz01iE0EkYkiyKAI6kc6TmmS3lzWov5iA",
        vec![
            "108.39.229.147:443"
        ],
    ),
    // Nickname: dockstader
    fallback(
        "790EB3E544E70809FA760DC793469FC5ABAF1E28",
        "3JJsKTEsc7Sr0ZMExU7PdViKAF/L502IUvFIoskqWIc",
        vec![
            "209.58.180.90:443"
        ],
    ),
    // Nickname: Venom131
    fallback(
        "EBB50442D1D826DBE9C61A9EE5E0A2CE44DD989A",
        "Y6lDdClPlQzhrpJhkknSvasvT/xlgJK5i/wspz8ouDQ",
        vec![
            "195.123.209.91:5092",
            "[2a02:27ac::4ed]:5092"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "808747E5308B3479CB91A61AC9D07075DEEF7FC5",
        "7yLZjB7gHaP6djf0Qgq4OtSUdJ/wB9xR0+bJsmzWBYo",
        vec![
            "185.159.70.47:46031"
        ],
    ),
    // Nickname: artikel10ams01
    fallback(
        "A14D96E6C4C3A5AF3D7E57AC0A85AE82BDFB0F4B",
        "5jZlVtCKVctSVQ6I/g4tqCp2WAtQVGWsX8rqlUpiaQQ",
        vec![
            "45.151.167.10:8443",
            "[2001:678:e3c::a]:8443"
        ],
    ),
    // Nickname: venezuala
    fallback(
        "84F0FEBFDFA8FBC6A2EA27F87EBB31F050AFD04D",
        "Wiu2eDVadsFOPpCQx5N8YB9wsR4WK2jsB6yZaFcXUGY",
        vec![
            "82.145.59.127:9001"
        ],
    ),
    // Nickname: Beet
    fallback(
        "287E1041DFC3A03E1650A61ADF580EA1C6BF3649",
        "G4Oya/G+cLRo5lNO+0G3C5R/GJ01Rgyya9alJqkvzQc",
        vec![
            "46.19.141.85:8100"
        ],
    ),
    // Nickname: KagamineLenQasr
    fallback(
        "F4F92D8B840C2D053197AC3EF9C58F3DCFBB20FE",
        "sHemSYgTZGwMcZ8ZNwpgJxjWIibrMg68Nva7a/jYfF0",
        vec![
            "91.121.86.59:993",
            "[2001:41d0:1:8b3b::1]:993"
        ],
    ),
    // Nickname: FissionMasq05
    fallback(
        "41427448C41642832130C2C29AF1FEAC3B3EED35",
        "VV3h6/m+jsfP4ld0+QtSzd4PLfvhss5N/iUogv0EirM",
        vec![
            "185.213.155.169:5753"
        ],
    ),
    // Nickname: Neryl
    fallback(
        "84C17F4EC57A17D0C4A13B99805A7DA325AC10FF",
        "gcA73xlaXhJlBbIGZy4MSfA0/L3RrmQu45/hvGzb9Z4",
        vec![
            "213.158.31.231:22711"
        ],
    ),
    // Nickname: guidemenow
    fallback(
        "16824F885D72B4FA7A5090E08D877E5404BC214D",
        "eQVZPQxRhs2/HxS1epGjER9pDujxaRnNURZX+c67cus",
        vec![
            "62.216.54.29:9001"
        ],
    ),
    // Nickname: descartes
    fallback(
        "E00764EDD2D5DA338CEA2EED8691E1FCAAF4A6E9",
        "TWj8HM3CDFUgt3+PjQSJUJjcr0zDsNro0hLlm15TciU",
        vec![
            "46.188.6.64:9001"
        ],
    ),
    // Nickname: Tory
    fallback(
        "4ECC88F957A6DFC262F2E4498C7FC022A712AE78",
        "xxfn2mgOckMJii8OEiuweYwBsLoNzKsZYOmbtsFoUis",
        vec![
            "47.144.81.21:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "9E298B955B91D5CE2AEAEBC6CA9858676D091F93",
        "eEb9ZHE/HqNCZ03Y+/4P2d5GFN57IaP581e0k4COPX8",
        vec![
            "176.67.170.192:9001"
        ],
    ),
    // Nickname: niftygorellik
    fallback(
        "DF390860B5610B8E99C5A78B4099A3705CD36B17",
        "G9mlLPfMundQYiQP8S4i/AUjVPBWzRmem2HW9L6pNYc",
        vec![
            "185.220.100.251:9000",
            "[2a0b:f4c0:16c:5::1]:9000"
        ],
    ),
    // Nickname: relayon0103
    fallback(
        "CD97DD0842A79184A7D057ECACEF7408C239C710",
        "ALZgJ4dZS1c94/wYE3IZuM+2xsnPhi10QdJT7HJ4zLk",
        vec![
            "185.220.101.22:30022",
            "[2a0b:f4c2::22]:20022"
        ],
    ),
    // Nickname: BeastieJoy61
    fallback(
        "CE47F0356D86CF0A1A2008D97623216D560FB0A8",
        "c1bbM446BkqMA3IoJsOqoJcCnQhDh7IM5oon2hdSIBU",
        vec![
            "85.25.213.211:80"
        ],
    ),
    // Nickname: intothetylerzone
    fallback(
        "2892073608985977DED33F98A9FA27A9C47C8B61",
        "uVzPfsqgapU2cRhWcYVIeeTWz1eyw3BBnNQaGR9xKKU",
        vec![
            "198.58.107.53:9001"
        ],
    ),
    // Nickname: relayon0346
    fallback(
        "50A0CFB654D39F420F52D362B1DF50A12B33D5A0",
        "N6AcuMoWP5HFYigr7X4XDWuzfE+GzCEAppTh8hi1hwI",
        vec![
            "185.220.101.206:30206",
            "[2a0b:f4c2:2::206]:20206"
        ],
    ),
    // Nickname: bartleby02
    fallback(
        "85041E7C5DF043B03F2C19421998F1751C002E49",
        "GOhSA3oyNoC7HMgU9YGRITeo2sf9xhbnRP0bn+VNsOE",
        vec![
            "188.26.207.181:19001"
        ],
    ),
    // Nickname: tORu
    fallback(
        "C63F4EC7437193BD6070D5CBD0EABBB610DD02AA",
        "3qSBocsOtzQrOK0K9JkIC1Dq+yyIxHRJ9Ffsg69CQ4A",
        vec![
            "54.37.138.104:443",
            "[2001:41d0:601:1100::218b]:443"
        ],
    ),
    // Nickname: PowerBalls
    fallback(
        "80F89CB42A1257A6145C1B1D6463C795CB99A6A4",
        "Jq0yqm3HIOK0xErka8+Z8l3hngn3g7mogBf1WdMwORU",
        vec![
            "173.249.63.227:9001",
            "[2a02:c207:2026:3509::2]:9001"
        ],
    ),
    // Nickname: WhitmerIsACunt
    fallback(
        "C841357CFA0F2CE96692EF21D515D6BF0B017036",
        "DXe0Zt6SuUsVY0LhwOuv3WEUypFi6RmOcAiO/JgAed0",
        vec![
            "185.142.239.49:4444",
            "[2a07:85c0:0:208::2]:4445"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "F91017B2C5A5AD3706B1A2DC8B1BC40C58633455",
        "xABaExZhojyo6RaCHRSuEafwOH1XyYWVmmJe5rQJHxY",
        vec![
            "198.100.149.77:443"
        ],
    ),
    // Nickname: ATRinRO2
    fallback(
        "CE001E45872376CB49EEF2A78519DA1E141172B4",
        "G4ErB+98RYLTR/rNnHCBseWCRFoyVY10kL2kuPx+uZI",
        vec![
            "188.213.49.109:9001"
        ],
    ),
    // Nickname: theWOPR
    fallback(
        "645C3F0545E0975A49F69EC272C0C3EA28586825",
        "KnaaR/cDD7+zw6CGTzagvJJM+aW7RRltTwWBVAOfyzk",
        vec![
            "212.8.243.229:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "91ADCDFCA830A1BBAD3A10377B25D695A92BF251",
        "2/d6BaatzsGpOwxa0l3ULqrYiiUF+rIuFtGDip5TK8k",
        vec![
            "145.239.158.234:9001"
        ],
    ),
    // Nickname: DoNOTbeEVIL
    fallback(
        "FB879E9F83F885D35594F85C5E42EC9CADD8461F",
        "1LwcptiUvP6bb1aXGQU4wxus5xWs9CVdsYNRs5ArbD8",
        vec![
            "87.151.147.113:9001"
        ],
    ),
    // Nickname: BeGayDoCrimes
    fallback(
        "1228111A6D4AFC619ED3A70079A3A0B678476A43",
        "2vMb0Lp/uGfiAbcm7F+plel31Rr1uZEGiDOOtvw/suM",
        vec![
            "23.129.64.239:443",
            "[2620:18c:0:192::239]:443"
        ],
    ),
    // Nickname: undisclosed
    fallback(
        "7D277B076A1A044F0FDEE9EAB02CFFF655C29894",
        "QMOfAz71u+4LS8itLadXJaBEiBgydGZL5maM3+l1p2Q",
        vec![
            "184.105.221.249:443",
            "[2604:b480:fff7::249]:443"
        ],
    ),
    // Nickname: bistrv1
    fallback(
        "F5B58FEE44573C3BFD7D176D918BA5B4057519D7",
        "D9j5zGbXzY12qLqK4nbS0v7ckNwcobGYgg+Qxm01GpY",
        vec![
            "212.47.227.71:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "CDB05CD0E7088A5A9B689A844252B4C681B74F30",
        "KS1q8qC6dRDcv+W3BbgrZq5ZqGOsjXCkBzg2MICoRfk",
        vec![
            "95.84.140.36:9090"
        ],
    ),
    // Nickname: HappyJap
    fallback(
        "A8BFE1E65C6DC3C7A50F8DFA0BF57F0A118144A5",
        "x09p1CbvuKHiPMKYeAbqUKgHE3sLMjeuQrpTueTA9BQ",
        vec![
            "71.200.64.77:9001",
            "[2601:14d:4100:452:ba27:ebff:fef0:838f]:9001"
        ],
    ),
    // Nickname: mimer2
    fallback(
        "1AA042AA8013B7C7853CE2A788537DF558498510",
        "avG1SylPRJIB/bPQcTXjBa5H76/kdTV/wvw+1yHwZ2I",
        vec![
            "130.225.244.90:443",
            "[2001:878:346:1cf9:446a:c4eb:4548:7071]:443"
        ],
    ),
    // Nickname: Miko
    fallback(
        "573EA7F927259DBF7DC6CDF0C99C592635AE686D",
        "h+9yDHDzEzqz/K2llA0ZDPhDzKfeBpPAZp1aovqXRZo",
        vec![
            "140.186.205.68:9001"
        ],
    ),
    // Nickname: iscariote
    fallback(
        "7B53DA28813258A20335C8E8985C05D0D089B441",
        "jNTKXAoqxK5Ze5KJCPjIrjg9rJhMHdqysMiyUcXcTww",
        vec![
            "51.15.142.0:443",
            "[2001:bc8:47b0:1b53::1]:443"
        ],
    ),
    // Nickname: schattenbahnhof2
    fallback(
        "CCCB01941013A05D2A9A3A5926C9011B427A1896",
        "Iol2xZNy3KBJ+1hZlwBWQ+WE6cybk0ZmXVCsUshmM8A",
        vec![
            "188.68.53.92:443",
            "[2a03:4000:6:e34b:7cf3:194b:368:22d]:443"
        ],
    ),
    // Nickname: SillyRelay
    fallback(
        "901592FBE2A2335F5DC3A5434600B9A4F9D9C68E",
        "hTWJCof906Tjun6WuOKDXmAWzzpcS04CCsE/291BNJU",
        vec![
            "147.92.88.67:9001",
            "[2604:21c0:100:1::cafe]:9001"
        ],
    ),
    // Nickname: voh3tooNgaiceiR7cah
    fallback(
        "D1F1C1A054C7F59D9F77834274F863CBDA04DC29",
        "fpcBBJ5F0nlPQinImw5womJHOa+hI3sej8H6Q6461HY",
        vec![
            "163.44.174.129:80"
        ],
    ),
    // Nickname: torro
    fallback(
        "A0E3D30A660DB70CA0B6D081BA54D094DED6F28D",
        "LfC0DgwkGRWg/tg6lP2ZA1r2SH0K2/Bc/n4x++4/BJQ",
        vec![
            "45.14.150.182:9001"
        ],
    ),
    // Nickname: vrijheid4all
    fallback(
        "A4A2FE36988069304CFF837064277FAB6348AF03",
        "qPAD6CPgQYNJvQqvqTxrkrJW8Amy9HH5fsThhrnLa2A",
        vec![
            "94.142.241.226:9443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "D2B81EA1DFCD59A7B255D31C2DC338065706A85C",
        "fDKO+MJjfTwjMOO2IEMbaBuVY2F+8gGKQyZJggPIKeo",
        vec![
            "198.245.61.196:443"
        ],
    ),
    // Nickname: rofltor10
    fallback(
        "3CB4193EF4E239FCEDC4DC43468E0B0D6B67ACC3",
        "3c5koajx8IV5RkBuLlll7KonUyZfmkHjeTYk0sijGdw",
        vec![
            "51.38.65.160:9001",
            "[2001:41d0:801:2000::f6e]:9001"
        ],
    ),
    // Nickname: Geheimschreiber
    fallback(
        "C69D24F9353E16D85E82B4A9E4571DFAF6DCF531",
        "8xkH6Lwm6SHFMuGm16LlAxliRYdjiFegrAECNvkF508",
        vec![
            "109.150.12.235:443"
        ],
    ),
    // Nickname: bosses1
    fallback(
        "15C3F39B273727B6AEF44975C5E6F8FA341C2F4B",
        "oDipt3J6bQz+F5NrI6rlw6D4qtSnJTHjhyPxzuoeXUg",
        vec![
            "104.57.231.27:443"
        ],
    ),
    // Nickname: hviv117
    fallback(
        "0485027A0A349D454D978F6C1CECDD29EA17769A",
        "uaWI4BMx3+QC7Aq8oBO4qtuK8BdZbJoXGvMj7AK7CZU",
        vec![
            "192.42.116.17:443",
            "[2001:67c:6ec:203:218:33ff:fe44:5517]:443"
        ],
    ),
    // Nickname: TOR2DFN01b
    fallback(
        "2F09BD6D9A2D5A7D6D26C17651CE8ECF0B7BA257",
        "Ufikd2Foi1pKYAs3ESq9zdN6GQEnzE40JvJ/qStAdbE",
        vec![
            "217.182.198.95:443"
        ],
    ),
    // Nickname: AllieRoscoe
    fallback(
        "CD5CF125FED4BE5DA5F259F75AF3D4DD182C54D0",
        "jjSXFh/yDRZXQSl5sI4HoSItQASm/MV1l7WZKgaWlH0",
        vec![
            "217.12.203.242:443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "736CD23D364941A7C23DE00FD21E44D16B50F388",
        "Q7rEzwxD/u6eZA5kqN38uww8CepTVqKhwCeFPJAfu0s",
        vec![
            "134.209.224.96:443"
        ],
    ),
    // Nickname: gork
    fallback(
        "F2899981E3A601A7B2DDC7DDE02C248069704D9F",
        "il40Q4Cf3mSXsxW9PXwOY37svdPig7uX4Tgt3q4GJuc",
        vec![
            "82.118.242.103:443"
        ],
    ),
    // Nickname: Quintex66
    fallback(
        "501F5C4AACABEBFDC6A23543379F19B066396946",
        "l0rq3W5vWhcdj1/JBkyyS93pmS8xRpW8CBrLK3rodTA",
        vec![
            "199.249.230.155:443",
            "[2620:7:6001::155]:80"
        ],
    ),
    // Nickname: Hydra20
    fallback(
        "86E479266EBB982E204009532ED460628689E5B5",
        "8yAKoCUajjQ8sQLq/NO5hVSiATC5j4wGpxPgE0mzXuE",
        vec![
            "193.218.118.100:9001",
            "[2a0f:e586:f:f::100]:9001"
        ],
    ),
    // Nickname: CryingOnion
    fallback(
        "5A9B2EC4C652EC4FF72C8C673937BE27B3486666",
        "xwCJPnbwv2I4QcbpM31lai6cjI5vfJ/seGDQqIJ7Hy8",
        vec![
            "5.181.51.52:9001",
            "[2a03:4000:3f:12:9460:76ff:fe49:d419]:9001"
        ],
    ),
    // Nickname: Lubuntor
    fallback(
        "D4A47678E58E6E38FC90F1D80FD19FDFE6C58D90",
        "OED59EJ4E1WQx02CQqSG0YIAvbMdsQubPytLeTvs98U",
        vec![
            "2.233.91.176:19001"
        ],
    ),
    // Nickname: relayon0136
    fallback(
        "97D2A26EA5C9972E66D23F4698E94DBDBA8F6C18",
        "1idUZ3wFSkxVk821Z3k4fbmgjdrGNHUHfg0bKrYbfMc",
        vec![
            "185.220.101.20:10020",
            "[2a0b:f4c2::20]:10020"
        ],
    ),
    // Nickname: ntrlTor
    fallback(
        "9E8FB4EFEF3A6B62D0F0152B0606753D413BE337",
        "BDIX3bP2w7OfbUfgJzygsSXRFBpVDS3KlnSGHeSAn3Y",
        vec![
            "143.107.229.120:40233"
        ],
    ),
    // Nickname: ShardsOfNarsil
    fallback(
        "5492E760648AABB7BEC08BC87E8F72F55FBBA90D",
        "ufGl5PbDEG16i/1iK2uytTL5mTCc1ZirPlJ/NduIVHo",
        vec![
            "75.176.45.87:9001"
        ],
    ),
    // Nickname: FreeAssange
    fallback(
        "18CA339AD0C33EAB035F1D869518F3D2D88BABC0",
        "ivgVuciWWMhcdkfsARugySe9KWrzGkwMYsfEqW31DPs",
        vec![
            "124.168.18.172:9001"
        ],
    ),
    // Nickname: kokopon
    fallback(
        "CC32A2079CEE3FFDE9F8E29CAB369AC20C2B5F0A",
        "i9DyNr5IBqRof4371Ut4QO12Q0BKHzsQY16kNN9x0N8",
        vec![
            "134.249.185.176:9001"
        ],
    ),
]
