/* type=fallback */
/* version=4.0.0 */
/* timestamp=20210412000000 */
/* source=offer-list */
//
// Generated on: Wed, 11 Aug 2021 12:54:23 +0000

vec![
    // Nickname: ElNinoRelay
    fallback(
        "2C74829C382C1363812FC2BF053122A9DCF6583B",
        "A4oCeCv0yaUPAiaAwYU4sL8yEqsl1C/zA/Ie6s3kf+E",
        &[
            "46.126.96.8:9001"
        ],
    ),
    // Nickname: tor1VaxariNet
    fallback(
        "BCC93B0ACA325374086A5100D02843A04EBDCC00",
        "kf8qZ71bjTjWOJ8fAl/Thn01itC6SaOjVC0gCvSMkyw",
        &[
            "85.214.141.24:9001",
            "[2a01:238:420e:ae00:1c37:63c1:24c0:ff75]:9001"
        ],
    ),
    // Nickname: x23tor83
    fallback(
        "1730E41B3B004479D4EF124B5364CC34CE86F4EA",
        "tBD6fa0iSdze5x8+FIWpgMhbh/taVTXyV3DTrVrnDTw",
        &[
            "185.76.191.83:443"
        ],
    ),
    // Nickname: owin
    fallback(
        "B6942C63F1A596E6557D13FC0ACF8475A0A2AD3F",
        "lf71DEXVZkE4gkx1qXurMaoTONawDAolCI64PefhCUc",
        &[
            "89.41.173.138:443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "552FBD8FC8E7C5AC05FC6F8C960BDAF1081413B2",
        "Jc90mABjLmXfKOaAsh/k4fVRBmIjpPjEDV6AYbfVqpU",
        &[
            "142.4.213.88:443"
        ],
    ),
    // Nickname: scurra
    fallback(
        "56781CCC9F6D29FEA148799AB588429C893A473C",
        "MH8XufjnwyHBPHqoe3QGbyvWZw2mmWc6nf0/1pC2JCY",
        &[
            "148.251.191.252:443",
            "[2a01:4f8:211:d4f::2]:443"
        ],
    ),
    // Nickname: UenoStation55
    fallback(
        "A932F56F69D24A96A0CBC4F32922A62DEFD28C77",
        "2Hiha0riWEk0jQWI5aI7Pm2l7nMtZPhOONuA6v+8lio",
        &[
            "51.89.143.155:443"
        ],
    ),
    // Nickname: octavsly
    fallback(
        "69497036653189531207746B3D0E4ECB56888F3C",
        "BV2Of7gINAQSVsVGLPk2eWWrMVKmJ9JQXrX7CkJUxsg",
        &[
            "86.80.108.228:9001"
        ],
    ),
    // Nickname: NikowskiThirdNode
    fallback(
        "973B219FDAC30873212D866568B30C44D57B32E5",
        "Dn52F0CQNR0Eb1968Ny26Bfed3arXgCWXG3+9Vw8RMU",
        &[
            "54.37.232.61:443"
        ],
    ),
    // Nickname: x23tor76
    fallback(
        "837528CA94748B72CE1829E4E23A7EAB232C30E6",
        "gXX5gWaMJ39O5GZCqAOSDtbVWT26PuKVrZ3+VJNR1So",
        &[
            "185.76.191.76:443"
        ],
    ),
    // Nickname: Assange011ruX
    fallback(
        "A9B28E4D4FB6A26B5B6D3EDED2655D836BBD4E57",
        "GOBjfh2xVtJY76ZpMmJ2JCPo9Ks2A2bU9gn95yzrQgk",
        &[
            "45.140.170.187:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "B22A56D8AE494A20CA0EB8457F3CAC54FC99ACCE",
        "qrNS8076DwfNrryfNaVxUnFcwhBVm+gLQefNcj5zFkg",
        &[
            "81.83.37.138:9001",
            "[2a02:1810:38a2:d400:ba27:ebff:fec2:3e7e]:9001"
        ],
    ),
    // Nickname: Ajorcel
    fallback(
        "4F95B7313679ECC000F38F870CF0CF39C7386C50",
        "zNkWCji761LWEpw0yBmZhabh6jynsNXjkkd2MQQ2JHk",
        &[
            "82.64.163.188:9001"
        ],
    ),
    // Nickname: Quetzalcoatl
    fallback(
        "6183B493ACFF41B28745CF0322E75AD7BDE4A48B",
        "m5uEbwHFg3mOmnphi2NwuZdBc7lUgyQQlYp0xYP0olY",
        &[
            "104.244.73.93:9000",
            "[2605:6400:30:f73d:de71:a4eb:1b99:9545]:9000"
        ],
    ),
    // Nickname: Rowlet
    fallback(
        "690FC3ACBBBC970309A9A0993EE12AF44C0C8E62",
        "K5Z3RmlZ71JvikfodT8wobuEPDTyPFYrQk7oDVj5ts4",
        &[
            "194.38.21.10:9001"
        ],
    ),
    // Nickname: orangepeel
    fallback(
        "DF6F2B91C93270771C8EC92D243A7CB6234244A1",
        "kCa8R2rBccI5v4Gm6Ed/QFsqBxz4Kp2dBqZQY0ddxyY",
        &[
            "58.185.69.242:8443"
        ],
    ),
    // Nickname: Starlight
    fallback(
        "0D8877392F2FF5AD8D8E5BC438087F02EF97B904",
        "GHRvTLnPdOb9GjZFOhs+RruNj+gRTf0XGwg6YY0wA58",
        &[
            "49.194.93.54:9001"
        ],
    ),
    // Nickname: PixelBullyRelay
    fallback(
        "289F955FA04BD224F18DED9D4766529705FBDC48",
        "hZVoSpFfkKPMaEk2JXqoQCb7Z9gpMyhxfm7PmuOsOjk",
        &[
            "82.35.159.1:9001"
        ],
    ),
    // Nickname: TorOrDie4privacyNET
    fallback(
        "9423A72BBC8B5C6AC9DE9F57735EB2B08E4156E8",
        "agV7UeZAUR8B7vlm/W/fcxxpSt59OOdz6bz06H2J5W8",
        &[
            "37.157.254.37:443",
            "[2001:4ba0:ffff:11a::3]:443"
        ],
    ),
    // Nickname: astolfo
    fallback(
        "9738F8F5C386CDAF5707D0DCED428F2813CA285F",
        "iSf1FnQKOAc8UZLt2D0uwovKaUxxIDEg3s4ip2BXNuo",
        &[
            "78.46.85.216:9001",
            "[2a01:4f8:120:1381::2]:9001"
        ],
    ),
    // Nickname: a9Exit
    fallback(
        "2DB8A946826D0CB4F5C3A8264628DD0F16F6612D",
        "+ZzTkLVLranmIiyn/u1w8EjvASp1QRfs6+4SJ0VUpio",
        &[
            "104.244.74.28:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "E12235C7310A4ABED3480E907F6D9BD1DC1E1D6C",
        "zpxTNPwGOy0paNtW5dHG0ttB+9pjjmGuYrulQoigtBY",
        &[
            "142.4.213.112:443"
        ],
    ),
    // Nickname: MrRobotLives
    fallback(
        "954B2AEA8FDCF0DF701A2EC9285640B929546DF7",
        "6IGhMM/TotfvGxERSOgjufDnljaVmBlGS13rJHSpOI0",
        &[
            "68.196.180.5:8443"
        ],
    ),
    // Nickname: lavandeluxe2
    fallback(
        "023DB955544865BB4D593DE66E89B496777DF0F0",
        "CMsNbHA7zj0NPaOcauFY0mfK+EBJYo7rLKSe37VxWZ4",
        &[
            "45.91.67.90:9001"
        ],
    ),
    // Nickname: mrrm87
    fallback(
        "25A3C92EB11A140B006695D0009F6EAEAF3C6785",
        "2hD0aUXqz3+TwpUY3SAQbgp1dOgx3EGxED9Btjvb728",
        &[
            "89.212.26.36:9001"
        ],
    ),
    // Nickname: alpha
    fallback(
        "5EB36D1BFC513A66F52A969AB23456E92D2ABB46",
        "FOgo9lZ6d3oOEYa6XtdneFfhf8auHcoXV0sCyoG97wE",
        &[
            "116.203.245.170:443",
            "[2a01:4f8:c2c:4582::1]:443"
        ],
    ),
    // Nickname: relayon0138
    fallback(
        "48BE372CA2104D2422D49CD321060E7F697B52D9",
        "FS0gSYF4RE7tXDC1b40HaVIQqlmN6Gn2EDLihsFbFik",
        &[
            "185.220.101.13:30013",
            "[2a0b:f4c2::13]:20013"
        ],
    ),
    // Nickname: fiedlerRelay17
    fallback(
        "FABA6394C790E96812D33689FAE90796FBA79AA8",
        "lb+BD77n7O3j1uVXqnoOtJKdgRv1FhvbryRqk0vnD/0",
        &[
            "37.221.198.114:9001",
            "[2a03:4000:9:533::2]:9001"
        ],
    ),
    // Nickname: GrmmlLitavis
    fallback(
        "8C00FA7369A7A308F6A137600F0FA07990D9D451",
        "L23HctgabSrEUrcIPyn57lbLCb6h0TOxoYlLovViM4I",
        &[
            "163.172.194.53:9001",
            "[2001:bc8:225f:142:6c69:7461:7669:73]:9001"
        ],
    ),
    // Nickname: F3Netze
    fallback(
        "E8AD8C4FDC3FE152150C005BB2EAA6A0990B74DF",
        "5lbkUyBKLAk+1zunDhv/Z2rGUXouCNh2fTZgQvHAcfs",
        &[
            "185.220.100.243:9100",
            "[2a0b:f4c0:16c:13::1]:9100"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "15B434A2AC13ADE9E3F7EE6C0A740A377300F1D0",
        "haL7C/LyuTdk2BJh8D64dizymKr3OmjW+sRRzNzg2Yo",
        &[
            "198.245.49.6:443"
        ],
    ),
    // Nickname: Zion
    fallback(
        "625743FAF41B791AAFC2D4BF859DA4AAA2E81FE7",
        "1kXzZm0sbXeDrhHlqwEVnu0Gd8uS0ZijcM92Jv5cd+c",
        &[
            "78.194.37.29:9001"
        ],
    ),
    // Nickname: Doedel24
    fallback(
        "2CE96A8A1DA032664C90F574AFFBECE18A6E8DFC",
        "kimMgG1+IPZN+YWZnN0aILUEq35NXvor9tW57mVJtPE",
        &[
            "89.163.128.28:9001",
            "[2001:4ba0:ffff:237::babe]:9001"
        ],
    ),
    // Nickname: brwyatt2
    fallback(
        "4E9796481C1E75F75D57E8C1FC8C8ED111433316",
        "fPZBpgVDCoL/O+9vkS5WAK+PjnToybqsgOJ0W3E0Z2w",
        &[
            "174.127.169.233:9001"
        ],
    ),
    // Nickname: 1chandotus
    fallback(
        "7DB8443AE29FBC450D34E55FA914F42BF929EE49",
        "v2QoeNImdN4VdbjOPfv4UDPRhu/HKWa/5paRRYVR7YU",
        &[
            "45.79.70.147:9001",
            "[2600:3c01::f03c:92ff:fe97:5ebe]:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "1E70B9253E33D32F69B380B7C5AB0475F22DD349",
        "a093e02ltNsiMmkWDAeG44JVMjqOCycHEmBsrrmkBx4",
        &[
            "51.68.173.83:9001"
        ],
    ),
    // Nickname: doukai
    fallback(
        "570520A8DB8D2BAA95A8AB438C7FB61FE9555746",
        "r3EazJCz5hNQLIRHuYFcsINt1drO7fUkp8GUWYVIARk",
        &[
            "104.244.79.121:443"
        ],
    ),
    // Nickname: DerrickJensen
    fallback(
        "E0023AC14180112A2FFF00A84C6049862BB3E6C3",
        "/nZxaO5TuYt7/xRvr+diIQzlrt6b4cMewJmqa55Z5W0",
        &[
            "147.135.112.139:9001"
        ],
    ),
    // Nickname: aergia
    fallback(
        "342A1AC764D89248E66458C077CFF668D05FFF34",
        "11gfi7hrbEXbeduCLAWdVuVQS1/w1MNjFU7u4PyPGMc",
        &[
            "37.187.98.185:22",
            "[2001:41d0:a:22b9::1]:22"
        ],
    ),
    // Nickname: sandman1
    fallback(
        "7B57933E29D520471D7E67AB48B06B62832828F9",
        "uUi6dRbdtI85lmQokEhmcuGunLndvDpjgEEm9HR/14g",
        &[
            "51.75.82.166:443"
        ],
    ),
    // Nickname: JimmyBulanik
    fallback(
        "8E76F1F6E8499CCE975C451560586A5F8BF0BFDB",
        "ITePiQxskUniqFVu5SURNPGTV7hxluBkBzDB/ss0y3Q",
        &[
            "185.86.150.58:9001"
        ],
    ),
    // Nickname: BeAnon
    fallback(
        "1D97A312D98C4D677112265659BD69A83C3AF9E4",
        "9eWZt4+B8NhDxfq1czB0tXkZOKHVC3ugESXKTScGBNY",
        &[
            "91.219.236.197:443"
        ],
    ),
    // Nickname: 1torexit
    fallback(
        "AED4A69836630A3375845006B5AAD03BFA3F96DC",
        "gvaE3GYfGWh5nWo7/QqumBwd1INiooFh1Q4IwrG4fk0",
        &[
            "31.131.4.171:443"
        ],
    ),
    // Nickname: spotyor
    fallback(
        "68514D6AF3A500C61E5C8A03B0C1E1ADDAC62462",
        "4MOs79TcRJ0lgB+zNppm+awbdfH8ovhbyZgbOpCc0kY",
        &[
            "209.141.40.46:443"
        ],
    ),
    // Nickname: FreeTurkey
    fallback(
        "A9EDB4EBF9EF5F3A129A58AE28EF92DB4B5078A3",
        "DvBO5uqlPh2Nbt/4I5W/EurMyp9YcM0jA84Piw8x0gE",
        &[
            "2.230.193.197:9003"
        ],
    ),
    // Nickname: Quetzalcoatl
    fallback(
        "2EC5EE348BD8D9D2E518B2CAEA9C671E2D5F77A6",
        "0v7JPJGUc7uf8mN7zqflx3diUy+59IEB8lUdHkXYu/4",
        &[
            "104.244.74.121:9100",
            "[2605:6400:30:f6ed:c6a7:9997:d411:cb21]:9100"
        ],
    ),
    // Nickname: flowjob04
    fallback(
        "DD0AA66DD9E4E71FFAFAB658DF8300F1CEEA0364",
        "Mgg+SWH5dBUaudpJwlzDdaVwNbprdHcG8biQREfa9io",
        &[
            "152.89.104.206:9001",
            "[2a03:4000:39:45c:241f:53ff:fe4e:45e9]:9001"
        ],
    ),
    // Nickname: winterferien
    fallback(
        "412767ECB0CEF7DCBAF8748DDBA8575860DD6782",
        "t8ALrXC/RfTdgzQFeYg3IvUqbrfYFpkaXVKV8M/F2PA",
        &[
            "114.108.58.201:443"
        ],
    ),
    // Nickname: hKnYTKYgoYx4JmnAwu9
    fallback(
        "3DB72310F6999555E71A09C3FCDF86E8E99118F7",
        "1w4KGsm1MpxKijaQr4URj3LNWkcnp3LKnaY2pEuSOa0",
        &[
            "68.67.32.32:9001"
        ],
    ),
    // Nickname: Hydra40
    fallback(
        "B12536F2F1BBFE0B47FAAD0D5D05BFAEC6C2DE9F",
        "XjQAj+9qMeqkkxfhFsIBc6Jojjt+kz3N7TfUFYKXtoI",
        &[
            "107.189.30.230:9001"
        ],
    ),
    // Nickname: corvuscorax
    fallback(
        "FFF4E4F51077370085A339B1F81A02BF3C2F52C9",
        "zkxUGwnPKLCZyXJYejfJK7UeJPb5bsi+owaB2/At4iA",
        &[
            "51.178.26.103:443",
            "[2001:41d0:305:2100::8550]:443"
        ],
    ),
    // Nickname: DTFNODE28
    fallback(
        "8E8A46FADE96BFEA4F16CC23A25ADC05E00AE1AB",
        "eDwSyq+U86SFgTcH6HVW9AbNHYNjPGItkduDGQ5SWAA",
        &[
            "192.166.245.82:443"
        ],
    ),
    // Nickname: bias
    fallback(
        "1A10F6E2BA45CA4A5EBAA6EF759FCBF4E8AFEEA8",
        "XEPW2s53MhjEfh5jPYeuiumgKsRrgTVRd16zwE0jXw8",
        &[
            "95.217.15.17:443",
            "[2a01:4f9:c010:7066::1]:443"
        ],
    ),
    // Nickname: Quintex100
    fallback(
        "521C30A968743B13E17E22E39BE52DA020FB92E1",
        "ysbgq+zVGm2N0C/0DQ0iio0uZeiT7mhYssEvY+rnsBE",
        &[
            "199.249.230.189:443",
            "[2620:7:6001::189]:80"
        ],
    ),
    // Nickname: kohlrabi
    fallback(
        "DE847D94E78B2E560AB87D272DC90192D3144F17",
        "raYZglOJeO7u0UcQgaVVEGAnLKs1XhHRCSf4Z1vWwkA",
        &[
            "109.70.100.15:443",
            "[2a03:e600:100::15]:443"
        ],
    ),
    // Nickname: torrorist
    fallback(
        "8699371415DC052A60BCA3AAD68E55D9B759CAE0",
        "hjofgvyURuti3iJQqfPwIq3JqEMA/jzqtyW7vSIwwXk",
        &[
            "185.73.211.3:50001",
            "[2a00:8dc0:aa00::13]:50001"
        ],
    ),
    // Nickname: rackhamsaltair
    fallback(
        "15483893699246724B8135CC6F087767EA89A2D3",
        "TUBqYiQ33fwrZ7fFuq5t9RAVI7VcDBvrEYOEG35b0AE",
        &[
            "37.187.21.49:9001",
            "[2001:41d0:a:1531::1]:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "EC4B6AF202EFE752C4D9E2FBD092C4EAE779ADA1",
        "Cc/6OtncO0fxYS/nafR20RB3Fkfd2QoyJxiAY+uLXRQ",
        &[
            "67.3.168.113:443"
        ],
    ),
    // Nickname: TrafficAdvanceNetw
    fallback(
        "5F48BA138AC6F7B42CC7A0B0D4012541DFEB9677",
        "4E/bI9rVl+SxKXBLiD5mSO87obUeLnYytvPWrYB2R9A",
        &[
            "5.189.148.225:9001"
        ],
    ),
    // Nickname: rinderwahnRelay11L
    fallback(
        "39F91959416763AFD34DBEEC05474411B964B2DC",
        "HnejKPp54H643Vkv2QsDZ6aN196Rw/1RWfIhyyobvAc",
        &[
            "213.183.60.21:443",
            "[2a06:f904:1:100::4b]:443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "63540827C4832D214984EA47B7A68C593F9F862F",
        "2yvwWSwBd6Gbk15KFNw7mhCZwIuK8M0MZblhqv+d0aQ",
        &[
            "54.38.92.43:9001"
        ],
    ),
    // Nickname: marcuse1
    fallback(
        "EFAE44728264982224445E96214C15F9075DEE1D",
        "s2w6QLaOQFL2tLQoHSS7+hrk42W8RmTK1Q4mp7uasn8",
        &[
            "178.20.55.16:443"
        ],
    ),
    // Nickname: EvilMoe
    fallback(
        "F4263275CF54A6836EE7BD527B1328836A6F06E1",
        "F2A1yzDIBPuz2W+0RdLorUXzLjfdLIIf9a+cEH8uCuQ",
        &[
            "37.187.102.108:443",
            "[2001:41d0:a:266c::1]:443"
        ],
    ),
    // Nickname: fleischgewehr
    fallback(
        "9B5ED3370E002AEBB2A9B25E3213C1817CCD2D88",
        "5gHI5nV6jELXIaYIkOprMNVJtIMFN1lAAJ717n6h0cM",
        &[
            "51.15.65.243:443",
            "[2001:bc8:1830:180b::1]:443"
        ],
    ),
    // Nickname: redsox
    fallback(
        "E0A3471C24C9021CC58FBF774203046FD2BC893F",
        "3Q4d0HpmXY7J7yl7rJYbLfExXBMA/C+62O3EOLLGibQ",
        &[
            "188.126.83.38:443"
        ],
    ),
    // Nickname: ENC2WAW1984
    fallback(
        "91094CEBDA0C921923EA4213A209B14216F09AC1",
        "i+2a1CfEbuC2nkbXFZxl99ZRezc5PYoorViyNNGZzHw",
        &[
            "151.115.56.33:443"
        ],
    ),
    // Nickname: relayon0210
    fallback(
        "28F4F392F8F19E3FBDE09616D9DB8143A1E2DDD3",
        "4M/pCad2pYGL7OJUeRWJYE8S1f32QUVY0iLoNKb8T5Q",
        &[
            "185.220.101.137:10210",
            "[2a0b:f4c2:1::137]:10210"
        ],
    ),
    // Nickname: WYSWYG
    fallback(
        "7BE9E2EF2BB41BB662D9A3CD68289B9E3DBF8A08",
        "eJ3K5EYfrvcqUOJ7/Upq7hVNV2wygejWSDDpvU1ZN/s",
        &[
            "46.194.163.28:65534"
        ],
    ),
    // Nickname: Zwiebelring
    fallback(
        "EAD250EE6D1BDB1BBACFFD1C3C262D59FD55A41A",
        "aTJfKEo56NSyA0bZDs64n0VMgc7IAC2TzmTS8/xnvSk",
        &[
            "85.214.196.178:9001",
            "[2a01:238:4306:cf00:ec59:d2a4:ac11:336]:9050"
        ],
    ),
    // Nickname: undervillian
    fallback(
        "FC773D88785CF34CF0028BA13C5CBD32CAB27AE2",
        "R5dF+MN72Wzhg9zy6UArfdQjrnjrBGJEQXk/CLpzwMI",
        &[
            "23.129.64.133:443",
            "[2620:18c:0:192::133]:443"
        ],
    ),
    // Nickname: relayon0142
    fallback(
        "957354D72042719C310A907FBFE42A3232C78757",
        "1gO7xSGpnXKB6aPIR9Xfqvn0Df6842x5u3XIHKvH7HA",
        &[
            "185.220.101.14:10014",
            "[2a0b:f4c2::14]:10014"
        ],
    ),
    // Nickname: eludemailrelay
    fallback(
        "B05B3AB0159238FB7AEB1BF08A406D6F31A45ADF",
        "MZiFWIFSFv8KN/5iHbvHiUnn3j1WtUU4rvYxZZ2KFGY",
        &[
            "188.127.226.102:110",
            "[2a06:dd00:1:12:a11:90d5:be:11e5]:110"
        ],
    ),
    // Nickname: FreedomFries01
    fallback(
        "07623013C3361FE566B71C8CFCC6483D7587A827",
        "CksBh9EVySQ+RVUyW/dd1cBcY3tzx5YlvCbDs5gdUOQ",
        &[
            "45.33.46.101:9001"
        ],
    ),
    // Nickname: SCSYSTEMSRELAY01
    fallback(
        "5D377009B7538DE1423C4FBEB82370040394A9FF",
        "EH3gq3VtOrzOUfgZhn1mr6m5FxUMG1C/tTcVb2SOUzI",
        &[
            "116.203.23.183:9001",
            "[2a01:4f8:c0c:ae0c::1]:9001"
        ],
    ),
    // Nickname: INSRelay43at8443
    fallback(
        "BC6E80744314F16054A64EE0F2302F082C929958",
        "7g6PIFjMsY3uQaa5O0b1B3FoD92nASCraY7W9w+/GdQ",
        &[
            "140.78.100.43:8443"
        ],
    ),
    // Nickname: dvbhorst
    fallback(
        "28D20B990E48FCA20857DBDF12997C323C125124",
        "18kUMiopDRskbyK/iYm4yvB5u1l7WJZdPwKq13zVuqQ",
        &[
            "78.46.202.212:9010",
            "[2a01:4f8:c0c:162b::1]:9010"
        ],
    ),
    // Nickname: raspitor3
    fallback(
        "19083549B3F2BFD96FAACA934D7872CD578A8B99",
        "41NIjSPBounT0M+mb3v7ZO1pqKvxBEsgEdMAH9c8bhw",
        &[
            "80.100.69.97:9001"
        ],
    ),
    // Nickname: Doedel22
    fallback(
        "8FA37B93397015B2BC5A525C908485260BE9F422",
        "dNfTwih0ggHtNuNyJN9M+xDWpty4e3kIlC87OgpYa3w",
        &[
            "89.163.128.26:9001",
            "[2001:4ba0:ffff:237::abba]:9001"
        ],
    ),
    // Nickname: 3735928559
    fallback(
        "A96DA63E4415E776FBFCCF3DA7154C804534B6E7",
        "hzR8909DIR3zPzglMeC638Ksjxl5M2EFlZCTHaJ6zPw",
        &[
            "38.39.192.78:443"
        ],
    ),
    // Nickname: toritoinfinito
    fallback(
        "C0417071C3754885296F4A5935AC1BC1CABDBC31",
        "dQmxJsRHRotB+8EXK7Dir68GdE97usfxLU5lp7l4sqk",
        &[
            "201.114.166.24:9001"
        ],
    ),
    // Nickname: Isidore
    fallback(
        "430672CD7162FA88AB49D891C38567799F346333",
        "ySno5/wVG/rQPpdrKn0RtKzUBOas1CAMetO2CtSVfo0",
        &[
            "52.214.94.163:9001"
        ],
    ),
    // Nickname: DigiGesTor5e4
    fallback(
        "8C25BA134D579B8AAF420E01215EB2CF06AAE907",
        "nMCn87ZoEJBmI7ZqIqvKm0DjT4VVicCuBjBZEQXlkzk",
        &[
            "195.176.3.24:8443",
            "[2001:620:20d0::24]:8443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "BB004C7F4C5C9FAE5E001864537F89388444F572",
        "5zUv6frGpw0nlF3nln6JhEJbbqI/gJRHuqTYANijevI",
        &[
            "37.191.195.28:8443"
        ],
    ),
    // Nickname: anomaly
    fallback(
        "188FC071EBD1901AFEAFC68603C63D43F989709F",
        "VPZqcXRePYgyj+oWC3WT+b7PQU1NM5u6yG0LSzWQtnY",
        &[
            "72.132.134.217:443"
        ],
    ),
    // Nickname: AaronSwartz
    fallback(
        "AB6072166366C2E245F95905310431357B581F9C",
        "jZ2EkmrbGHDRN6hPFvMgVot6/Skzb/Ou8WtjEfWXmBs",
        &[
            "104.178.168.242:9001",
            "[2600:1700:c0:5678::9001]:9001"
        ],
    ),
    // Nickname: mikrogravitation03
    fallback(
        "DDC3D816F2B229CEFF613E4D912CD79EE34024EF",
        "Fgj5jn6opxdOA407Ijp1BE3vTmbpYKx1QghhjZ/wOf0",
        &[
            "45.14.233.160:443",
            "[2a0e:1580:1000::2dff:fe0e:e9a0]:443"
        ],
    ),
    // Nickname: oromis
    fallback(
        "F604131DCC4303E51DB876A017A3DC9684FD626B",
        "yEFRekS1Y4Zj93N0wzG2roRSKN5GMCxXMss7ZVI1OZo",
        &[
            "217.112.131.98:9001"
        ],
    ),
    // Nickname: Lule
    fallback(
        "FFA72BD683BC2FCF988356E6BEC1E490F313FB07",
        "1XEqrNow2olJOwX09N2/ixwregJsPECgqGAOvNMfL5U",
        &[
            "193.11.164.243:9001",
            "[2001:6b0:7:125::243]:9001"
        ],
    ),
    // Nickname: Potatoe
    fallback(
        "86FBA753C8D25653E086B98FFF8AA084F862DB67",
        "T5tYkv8OvfjklzUhJbwXlfcdC7mZlU15f5f4KHPMxsQ",
        &[
            "139.162.232.28:9001",
            "[2a01:7e00::f03c:91ff:febb:4d59]:9001"
        ],
    ),
    // Nickname: yawlimit
    fallback(
        "D4EC393C60D1A1AE39C09DF42F48664CF1DD7A36",
        "TPRHYI4hxEKKX9LmwnJA/TQx4x5WOdbPw/xJZ40jKy4",
        &[
            "82.170.235.23:9111"
        ],
    ),
    // Nickname: RelayStation
    fallback(
        "103336165A0D2EFCAD3605339843A0A7710B8B92",
        "5b6hsf7pfW4hj6Gs03JKrqGhoULvFNi/sRPl7pSeQQY",
        &[
            "85.195.235.248:9001",
            "[2a02:168:a403:13:5054:ff:fe21:7c4c]:9001"
        ],
    ),
    // Nickname: Doedel21
    fallback(
        "AE6A8C18E7499B586CD36246AC4BCAFFBBF93AB2",
        "20+J5gvHvuMgf/w3PszLi9hZVIt2I7siq9xwyd4b3W4",
        &[
            "89.163.128.25:9001",
            "[2001:4ba0:ffff:237::10cc]:9001"
        ],
    ),
    // Nickname: ridin
    fallback(
        "2CE9BE1FC88B9D0FA03F387C9E4F000B5D4B2AE9",
        "VrnxVXjLuT0suMHsWdQbnWOcIXOqKXcHcTcOnKFQJLY",
        &[
            "51.75.129.204:443"
        ],
    ),
    // Nickname: Air7jyl
    fallback(
        "716EE92A2E93ED69113D8F81E98530BA9A30DC31",
        "DICSFM+J0l2/SlF6YCuvSodgqHE3GzxkPh2dnMpTqBU",
        &[
            "95.154.24.73:9001",
            "[2001:470:1f15:770::2]:9001"
        ],
    ),
    // Nickname: relayon0132
    fallback(
        "906DCB390F2BA987AE258D745E60BAAABAD31DE8",
        "J0rQQMcx2miXz3MtkRXW4x/xk7TUfM7QVE+xDHsE4F0",
        &[
            "185.220.101.12:30012",
            "[2a0b:f4c2::12]:20012"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "3314200AC2BF60FFD828114F4A23D444834F14DB",
        "5Kc1/YVaRb6y9poCoLZk+dR/Qp4kITw+F5j6VsR3yo8",
        &[
            "108.16.117.27:7936"
        ],
    ),
    // Nickname: GoodColours
    fallback(
        "1E825573F8EFD5635E5C1E3B85CA647CFC84BA83",
        "xkFtPnml5agQ4+4iK1s0OZWYpXpVzG9V8n8Gymf0gOQ",
        &[
            "23.105.163.117:443"
        ],
    ),
    // Nickname: INSRelay15at8443
    fallback(
        "70882B116C73BE323036D824315A050EE796C445",
        "pH7elMwQNTFzCohr6D9VhwGPn0bbNZG8V8nilQcd4wY",
        &[
            "140.78.100.15:8443"
        ],
    ),
    // Nickname: RToRpi
    fallback(
        "158D411B51D313456D45EF66D099585976CCDD6F",
        "hnCJCfOo4xFiPw2FaGSNpgE1CI8Y/dNIzox0sxIrtJ8",
        &[
            "195.206.105.227:13526"
        ],
    ),
    // Nickname: gbhfmoldrelay
    fallback(
        "7555DBD9732EF66F0F084C41DFDA401B6D036505",
        "cAFj+DY0pXF4kW+ZmD3g2YQepxULJHIo7zoE1rNDKPw",
        &[
            "91.208.162.203:9001"
        ],
    ),
    // Nickname: torpidsFRonline1
    fallback(
        "C91102131E6B9CECFC56C4A29ADA4E638D7872F7",
        "GLkrhnqNxpiYFiS3dtwtCSq6gSo/pGJc9zA+o3J+uJg",
        &[
            "212.47.254.236:443"
        ],
    ),
    // Nickname: SpookyRooster
    fallback(
        "E9BFB31EE1D7060EFAE4A52C2A148D9C4974A7C3",
        "F0BqwpLrudAq0ZkD0jN78ACJpeLLqc0OqzGyCT/quNo",
        &[
            "51.15.41.39:443",
            "[2001:bc8:1824:326::1]:443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "ADBED8B751D7D63397FF3300BB3DE76141AA168F",
        "Q0UZGFVwFNkxO90Z6b4K9f7TNrwhc/vjM/XAkK3ZR8U",
        &[
            "51.158.147.144:443"
        ],
    ),
    // Nickname: leysen
    fallback(
        "6F1A2314C4A1ADEDFB7D419B6BB10D7BC40119F6",
        "VDVRZt/zNiq7N9s72fBXT5wm95VDQC7i49j7d3QdAPE",
        &[
            "45.125.166.58:443"
        ],
    ),
    // Nickname: Walker
    fallback(
        "D9EFB3D96A7C2E93AA7CC539086D6E1DD39455B1",
        "pJq1jBoDYTdiB7UXtgxnW3/EXENyLbdpl3gCFqCE/f8",
        &[
            "45.153.160.130:9001",
            "[2a0f:9100:110:a::82]:9001"
        ],
    ),
    // Nickname: FakeVolleyball
    fallback(
        "950134F4ABA3291EEE4E7A2F26546DB7070776A4",
        "MUc321Os7A81Wg6N1DDGdfwUL6rSoJ5ItRkL3iysojY",
        &[
            "195.123.212.228:9001",
            "[2a02:27ac::245]:9001"
        ],
    ),
    // Nickname: FriendlyExitNode5
    fallback(
        "A00E900534DFF76371064C03714753EAF8B88820",
        "+1OAyoIuEn1W9rdMw4THwJ2c/tD1WovUt0dTGSG/CSQ",
        &[
            "198.98.57.207:443",
            "[2605:6400:10:449:d588:761:3910:8268]:443"
        ],
    ),
    // Nickname: stoychev
    fallback(
        "C5BF27560E4B007365FBA96D32F9E74614218C8E",
        "tcdgpud5LCK1cGQ/HkJOc2j1uCDYZe/cyZ3zbV5uxI8",
        &[
            "104.238.167.111:443"
        ],
    ),
    // Nickname: th00ht
    fallback(
        "28B39D67BD18D13694DE03679EA4A864EB6977E9",
        "BcKnLV8S46qBuhstaT7AYCLAJuj8OMMpVoOJAZeMC1Y",
        &[
            "83.97.87.182:9051"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "55F3D29D53F3ABB6CF2F6C2FBE8D6A1B131D0275",
        "vG8uDcoGgtBHl//GtiUEkUen1cnr0zHE7OSyYI8r3rs",
        &[
            "195.154.243.182:443"
        ],
    ),
    // Nickname: myNicething475b
    fallback(
        "954A874584F009EB7D14D48362FF9AEF82FF6200",
        "ee3znU4qU6LHkZOmOALQYUhGTJO8YaOw1LoSZHrQd4Y",
        &[
            "91.160.55.21:9001",
            "[2a01:e0a:d:c540:4bfe:636b:b21c:42cf]:9001"
        ],
    ),
    // Nickname: VrijHeid4
    fallback(
        "C03209F54BC299927CA7581147434F439F37CACB",
        "1h1A2XckQeHS0XDqJIi8d+yKB3Acn0EfsfbTAxWXf24",
        &[
            "94.142.241.194:9004",
            "[2001:678:688:2::2]:9004"
        ],
    ),
    // Nickname: t1r
    fallback(
        "525EE34C1A7B89AB9DF585246DE30E32702913F5",
        "rAjI/SmHecAvxbKslHKDsJ/hiWTdI26YGE++TvVIoe8",
        &[
            "144.91.125.239:9001"
        ],
    ),
    // Nickname: minotorus
    fallback(
        "7E8BC43AE75EAE16D7EC4676F4A5C355F454B809",
        "/GymgUl4G7M0f0XMXbuQj5mnn8ls77L/n6kV42hJB2o",
        &[
            "94.23.194.134:443"
        ],
    ),
    // Nickname: goodvikings
    fallback(
        "D7A80E95892AAF51FF24CF7C2CE49311931B55F7",
        "kZshqhFhk5sRxHMVZfqw4C3uPNmb2bVxA/am/q6z5sU",
        &[
            "198.50.128.237:9001"
        ],
    ),
    // Nickname: idideditheconfig
    fallback(
        "8A2CCF9A354EF89C08CB0AE2DD7F7E8418ADF713",
        "aNvQDUnAV52T7AZ8y2RmCpYMfabjZOQxPys91ICGJfY",
        &[
            "80.208.150.185:9001"
        ],
    ),
    // Nickname: uzieka
    fallback(
        "54DE63F4587058B79152A75A0238D7F7A0279215",
        "U88bW9b15bbm0XaYR+uDSbffTH5aGNPH5P71srtjLmc",
        &[
            "192.36.38.33:443"
        ],
    ),
    // Nickname: Assange021usX
    fallback(
        "22658368E5AA075AEAACC19075ADC19670A77165",
        "bksAjBjEHjxfUIFYbRi8aL2fe7y71ZdGeyvksbAEn3A",
        &[
            "107.174.244.102:9001"
        ],
    ),
    // Nickname: TotorBEx
    fallback(
        "45DFAB9E1BD65DEF326CE0CB300E6C6F410A67F8",
        "q9Ktyb+d0ZtRzGKfMjTdvaHvw3SJ16mYsjLHkM2S4IA",
        &[
            "82.212.170.79:9001"
        ],
    ),
    // Nickname: mac68tm
    fallback(
        "155513DAF42E18FA16FCE77D08417E460785A95B",
        "n0zpz24Lsy0Nh0aY6ujtFW9g9fIoCi/UV/0AXNmw+XE",
        &[
            "2.29.35.45:9001"
        ],
    ),
    // Nickname: Handlebar
    fallback(
        "6078F300B379D8DEBCF02DBE80881C94777E24BF",
        "lmnqeK4YiWiBX4N6gLq3DNf3KW1e4WT7VAEcfXk2ygM",
        &[
            "198.255.21.2:443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "1489CEB120B3DF9CDF1EB5152A65F8C5F4B9E0F3",
        "uVwRK583SAdRzBsRTV7U8TJ+p2xpT0qBmaCBVi49aos",
        &[
            "198.100.148.106:443"
        ],
    ),
    // Nickname: vrienden
    fallback(
        "A4436E70B8D7E7C5482EFCC55D53D39EC6AE905F",
        "Pt1o10q9ndtowYB6EglD49mpeq//Ue+jxwzwSLchUb0",
        &[
            "51.81.56.229:443"
        ],
    ),
    // Nickname: Auroch
    fallback(
        "8CA16E878293D11F0E0803E5FC09F93A5C666889",
        "3jmiFjQLY6JATIb9J0U3Qjwaqb5c+Te45vqqLmxChZ0",
        &[
            "178.17.174.198:443"
        ],
    ),
    // Nickname: bynumlaw
    fallback(
        "78E2BE744A53631B4AAB781468E94C52AB73968B",
        "i2+wvNy+u/HqNniZA/4Wqxc4m8luIX5b0CR6S6Q+izY",
        &[
            "104.200.20.46:9001",
            "[2600:3c00::f03c:91ff:fee2:4963]:9001"
        ],
    ),
    // Nickname: realestRelay
    fallback(
        "934788C0B6DB4F1B6C45B1BC9E2EBBC79FFA2CEA",
        "2f73im505KxC1CChkcK15s8kYcGTvaNCO9KZsqlvLtk",
        &[
            "150.136.244.162:9000"
        ],
    ),
    // Nickname: cowcat
    fallback(
        "C90CA3B7FE01A146B8268D56977DC4A2C024B9EA",
        "fdzEqE9eqjqeSKn2ssxptHx47pLVyR1RUHfgeJWYZOI",
        &[
            "192.160.102.165:9001",
            "[2620:132:300c:c01d::5]:9002"
        ],
    ),
    // Nickname: cybr
    fallback(
        "7DA31D79E52D12685BBE8544E3C557F176B0FC84",
        "E3EbWFXFjCluMzUhj6neEY4IvtVU2zOJvG5biJItNSQ",
        &[
            "37.221.193.44:9001",
            "[2a03:4000:8:3c1::9001]:9001"
        ],
    ),
    // Nickname: 4punk7e3
    fallback(
        "F42FF0E095F23AD253622272F984649DDEEB402C",
        "sq0uk5mqno2rFjpgaAQnr/bC7o1Ce317TKP6PXO81t8",
        &[
            "45.91.101.18:9001"
        ],
    ),
    // Nickname: Blazkowicz
    fallback(
        "BBD1B1A22695396C75DFF338A8FF7A12804A607A",
        "6iIPXUcGnLZ0MrMCh7qRq4yyZ/mulBkhANTGsu+Zzvk",
        &[
            "178.162.194.210:80"
        ],
    ),
    // Nickname: rinderwahnRelay27L
    fallback(
        "95C8B9418E74F3FF80E5C3D3AF7F03156FFBBFBE",
        "XFqz9UJVCGXSn7yJGeeJQgeqs91kPIguAiGmEqdX1mg",
        &[
            "185.173.179.18:443",
            "[2a0b:6900:0:1::1d7]:443"
        ],
    ),
    // Nickname: kerly
    fallback(
        "3BB035514F8246AC367B5370F4FE120BB11D8C6D",
        "KVXhPk5FMuiCvSJ7GawRHsbo/Wm/zSOqx2r39RoTJbE",
        &[
            "93.115.95.38:443"
        ],
    ),
    // Nickname: Champions
    fallback(
        "83B5DB940A719B67F5BF616FEEC9D8D4F764D1AB",
        "6ASQGFq+zR/BPfTq0DGajZvHkArcKc+5xveZblxNIAE",
        &[
            "68.14.177.196:9001"
        ],
    ),
    // Nickname: zwiebeltoralf2
    fallback(
        "509EAB4C5D10C9A9A24B4EA0CE402C047A2D64E6",
        "O1MbXsxCb4A9rI/I6bnPI3Ds+XdncoMOSmTakJRAZrU",
        &[
            "65.21.94.13:9001",
            "[2a01:4f9:3b:468e::13]:9001"
        ],
    ),
    // Nickname: openredirect
    fallback(
        "7AAEE1FD80A24C377FE62A7A16B5D8042DA009CF",
        "hKPUnQUq7B8v/AMlAbguBrPXC1eH4sC0+wXRYlQ/Zhw",
        &[
            "46.38.254.223:587"
        ],
    ),
    // Nickname: relayon0144
    fallback(
        "619349D82424C601CAEB94161A4CF778993DAEE7",
        "I+9TMvGEzyjW9k90+x7H48v964mYTAjJeD1E0XO/t58",
        &[
            "185.220.101.7:20007",
            "[2a0b:f4c2::7]:10007"
        ],
    ),
    // Nickname: SanitaryLandslide
    fallback(
        "064D3C4CC1B854839B0979FE1C2F05ABAB7F9D68",
        "e6yWJ/SpKV5rg09QMEvkqEkzwq1az9HRCJuLNZdcCL8",
        &[
            "104.244.73.126:443",
            "[2605:6400:30:fa6b::1]:443"
        ],
    ),
    // Nickname: HYS2
    fallback(
        "FE88339058BACA3DBB947E3C10C37885A0E2F405",
        "4JqBvTXowIsAOds1OA0aLrKqtkYGRSSLBrljC/11YM0",
        &[
            "179.43.160.164:9001"
        ],
    ),
    // Nickname: DTFNODE32
    fallback(
        "AAD6687B71EDDD12DE38DFEEA1A6B089C91F5EBC",
        "L0xxULMARrbKludVRy2AKLxcsPKpEDVN5UVoucDgygo",
        &[
            "91.245.255.4:443",
            "[2001:ac8:a:6:0:2:2eea:9949]:443"
        ],
    ),
    // Nickname: DFRI0
    fallback(
        "DD8BD7307017407FCC36F8D04A688F74A0774C02",
        "3YzQBY0tjBYayCeyPJVGtw3sG7D1YSxXI3Gn0QfJeFw",
        &[
            "171.25.193.20:443",
            "[2001:67c:289c::20]:443"
        ],
    ),
    // Nickname: Labitat1
    fallback(
        "B2380704C53947B1D72E7CBCD361E73901EF7444",
        "7A9Q/IBLxdbYuGntuyxyNrJOvS5WpKYdhNYVGkQHO2A",
        &[
            "185.38.175.71:443",
            "[2a01:4262:1ab:20::71]:9050"
        ],
    ),
    // Nickname: Piratenpartei02
    fallback(
        "856B7EFB7E09D02A29DD2FF024B7E1EFE21FE9EB",
        "kQTD+FHDf4pXyE6qS4dfjKfpxBy4X2R87sxcd1UaIIo",
        &[
            "188.68.46.245:9001",
            "[2a03:4000:22:175:a452:acff:fefc:987f]:9001"
        ],
    ),
    // Nickname: RunningOnFumes5
    fallback(
        "2D2DEFAF19F705EA2978E616F740B771444A4C3D",
        "JmicBw356UmLHBEzW1zx5f/hbtJFgWmaeYvzQdPuFSA",
        &[
            "176.123.7.102:443"
        ],
    ),
    // Nickname: nodvrelay17
    fallback(
        "30CA5BE503177D8932FB312A49505A5737D8E409",
        "XHyupuo0COxZ2Z/z7zOPvlQ8UpJkKofCaKbyJ9zyW4E",
        &[
            "45.62.210.72:9001"
        ],
    ),
    // Nickname: C3WEyeOfSauron
    fallback(
        "18EA6AFA3609A0B24752FBF411A2DAADE27DE129",
        "MOgUYt959VlaMyayF8BzqmYDBJMhSpbfpU1MgS6JY94",
        &[
            "37.252.188.180:443",
            "[2a00:63c1:d:180::2]:443"
        ],
    ),
    // Nickname: thorchic
    fallback(
        "DFCDAF8A65F523212B1E4228B61815E72614D25A",
        "bwzQHPyYumixi1ZUOFBHmGP/o2BTRZ6bOaDlVhIGifk",
        &[
            "83.243.68.194:49005"
        ],
    ),
    // Nickname: AEtherC0r3
    fallback(
        "080BBF9B14454976FDEAD1AD620A04388F5A21F8",
        "pbRVxvjZTgZN/zPKbw/G0Xffi0hi0HDxAwG7gEpGuVs",
        &[
            "83.212.102.114:29950",
            "[2001:648:2ffc:1225:a800:4ff:fe50:934c]:29950"
        ],
    ),
    // Nickname: atoratvm
    fallback(
        "9737BEB02DB9FE6A89F2A022081FB7DDAC751AEB",
        "UDsKYcnucj/SNlORiB7xeg7nPH9WjOXBr0JBdA/XBbg",
        &[
            "37.218.242.84:8443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "1D81272219B679D511930499AD8286BCD8F6C445",
        "D3wRh4CyGGO4N/APWuqc8KYuvxCNaw76Zn9vKY4XgZI",
        &[
            "37.191.195.28:44100"
        ],
    ),
    // Nickname: TRB1
    fallback(
        "699653E5DF094B56775275F8A4F4BFA7C5BD5E2F",
        "hNHKDQZPrHRmwpSzyp+O5Ixab2+PcufWooCh9duxz3g",
        &[
            "178.170.10.3:443",
            "[2a00:c70:130:1::506]:443"
        ],
    ),
    // Nickname: ulula
    fallback(
        "54A403A1B015F6E5A641AD121530966BD873136E",
        "ATR5BA0vrrThhalLyw5z4omKC3Ryqgt+wKhWVNzEfts",
        &[
            "81.6.43.252:9001",
            "[2a02:169:200:d::15]:9001"
        ],
    ),
    // Nickname: Ichotolot62
    fallback(
        "7600680249A22080ECC6173FBBF64D6FCF330A61",
        "np89gXLD3ufDOjtjZBimLuRTiWhSdqX2Y1OTqJuUSLE",
        &[
            "193.108.117.209:443"
        ],
    ),
    // Nickname: debaze
    fallback(
        "95F22A129FD1EE5BFF95218DDBA838BF6DBBDA7E",
        "O8nGV0/DGNGCrlIpnhmCV5uGiQ/fMAiLVIJfHOOLC2I",
        &[
            "92.243.0.63:9001",
            "[2001:4b98:dc0:41:216:3eff:fed6:a283]:9001"
        ],
    ),
    // Nickname: Islay
    fallback(
        "F4873B3EC3325B81DC36C7E38AD3A5ED12B2F339",
        "Kc4Gfn4pyl18Fy264BhfsDF2w9W873h/wlv0ZwrJy7k",
        &[
            "37.187.23.232:80"
        ],
    ),
    // Nickname: m0rix
    fallback(
        "447A24F3402C4774D89E7AAD2D876D0BF64E3267",
        "30U6420pYN5/jpyCA0eEbfHhXW169qOxmeaiSeHDJ2Y",
        &[
            "91.132.145.245:9001",
            "[2a03:4000:37:76e:68f6:30ff:fe7c:a4]:9001"
        ],
    ),
    // Nickname: Styx
    fallback(
        "1316EE0CEBEE45E1EF4942927EC717E1AF529A68",
        "roAVcDDRwkP3vwq6z61t5en68706+9XIZyHobmoS+Zs",
        &[
            "31.209.7.91:9001"
        ],
    ),
    // Nickname: geekboxNEO
    fallback(
        "81893D8444F0C9100CCD963BD0D62BBC50121D14",
        "E6qtfuSuKygOX9A8nE5aOGM6t2+3MTSA64R3hU1nrco",
        &[
            "95.216.118.16:4223"
        ],
    ),
    // Nickname: trumaine
    fallback(
        "B63626A3CA6F0521847853DDEC6D4044C80B903E",
        "LxPw0W6qskVW0zuG0dPv8YrE9lw6qmymhptDMi9P0Vw",
        &[
            "79.124.7.11:443"
        ],
    ),
    // Nickname: DjMiddle
    fallback(
        "467D7417FFA611BC20227FE347494CE5F61218FB",
        "ropF/OdD5A1jZ6ssJ3C4kHrtggS9pUXOOfZ35esmtZ0",
        &[
            "173.249.57.253:433",
            "[2a02:c207:3002:8283::1]:433"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "2E5B5397CDD7F02798F9713B2C3D85C3FEFBAFBE",
        "litSWqR8TOdX+7qTq8GEDA+tLnnPDvKzOf54VtVswiI",
        &[
            "138.197.171.88:9001"
        ],
    ),
    // Nickname: nicknametor
    fallback(
        "AD1FC4AE877B2FFEB3C84F1A6B76E9B057AAEF4E",
        "QnDexV/BDRPTxXUmZdS7S8Yj+08S+OjsdOKMoaq/6IQ",
        &[
            "88.198.112.25:9001",
            "[2a01:4f8:c0c:53fc::1]:9050"
        ],
    ),
    // Nickname: SPFCFutebol
    fallback(
        "947FFF456CFCEF5DCAB09422E1945A8D21AEEC62",
        "XHstZ0rA36/mqGFTAZOn9+j/GhblRv+zKuueD+n9TCM",
        &[
            "81.17.60.24:9001"
        ],
    ),
    // Nickname: fiedlerRelay08
    fallback(
        "62274AC17DCCF4030A6AD8CEBED0C36E7B8592D8",
        "KDnnEU/i1NIc58vC1FYhluhg2eLf3jjk6AKky+U+RKE",
        &[
            "185.233.107.110:9030",
            "[2a03:4000:24:829::3]:9030"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "E03E581AA42A211F69DC63608B1980F10AE52C26",
        "VzMaJk2BPBuKFAuzLBm6S7SvOTLPBkaTKBTJZKPA7dQ",
        &[
            "37.191.195.67:38443"
        ],
    ),
    // Nickname: Dragons
    fallback(
        "F001CD2A9E27B7E3ECD120951CAF968213967B31",
        "cD97EIC/NQD8Vqiri9jRNhcDnYpkdxByj0egNv5KkZk",
        &[
            "193.182.144.53:443"
        ],
    ),
    // Nickname: tethys
    fallback(
        "CE8AE3563E13106A46EAD09A65AD70A5A097998F",
        "Bh8sbRh8ChOrdoLzU3hLbaqeSamgkkBHRoPkx//dfio",
        &[
            "51.255.106.85:443"
        ],
    ),
    // Nickname: tirz
    fallback(
        "5C86A09946A49E09AD64A14636DFF91746515175",
        "c6/uk7M3zmjFGiG/Zb29IFH0KLMgEVZbWpoq5Wj8U3o",
        &[
            "51.159.139.61:443"
        ],
    ),
    // Nickname: Harambe
    fallback(
        "34133CC3192CF7538089B14511400DF21BA5A077",
        "3DdNiHMxNeO7dLFGay5MRPAmVijiqaxJ7O7ae2IpTng",
        &[
            "71.166.42.70:443"
        ],
    ),
    // Nickname: arbitraryTessa1
    fallback(
        "4D70F05DD308A2EA5B671E440879BFADAC92860F",
        "xjiWO6Lt0aDEfSumxJK0z4qxo2R0Q48RD2VqUulPiIQ",
        &[
            "95.216.19.207:21",
            "[2a01:4f9:2a:1430::2]:21"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "1684B30AE2ADD371E5D3A8B3F28ACA4CE9CA2E00",
        "pDAsBveFOMGNQeUwxKTHB5kU4JFbaFK8ClLIGYUAs5E",
        &[
            "185.86.150.133:443",
            "[2a02:7aa0:1619::94eb:3758]:443"
        ],
    ),
    // Nickname: plan9leia
    fallback(
        "FFBC69467B37D6AC66598BBD295F9B0D74119ADC",
        "SHEalLb+JC788DfrGLdyOGsGkm1CyOlYgE09gZ5nO2w",
        &[
            "213.239.217.68:4433"
        ],
    ),
    // Nickname: prrlvrRelay
    fallback(
        "5DA4305BD06BD6F6A30BB06C34C251E256AC1328",
        "eqVvWfc060yHeFEAs9N9yAcjSbBPPrFvlflaGTNerbo",
        &[
            "51.178.17.128:9001"
        ],
    ),
    // Nickname: Gu1nn3zzRelay
    fallback(
        "7C5C0E83CA290FFF6D5E30D9E0E3FFC9BAE0D0C5",
        "sa3A59vc3kBoNI9eLDObDPgCinelFPpkNdWiViAHzzk",
        &[
            "212.47.236.95:443",
            "[2001:bc8:47a0:201f::1]:443"
        ],
    ),
    // Nickname: ss23voyager
    fallback(
        "CB81BCFD44FC142616BB5983648BD8AF01930789",
        "65aauuRFWdTjXpbQtkVHpTDiA11Mlgk+v9JupkO3Yis",
        &[
            "114.23.164.80:9001"
        ],
    ),
    // Nickname: sosa
    fallback(
        "EDB5CB4E8609599C98F1B5C939B26B2A9BA9333B",
        "PAT9y2OHay0Bw+Ck1gPwCUFja4A4Hbjqexhe1Gx2tyk",
        &[
            "179.43.156.214:443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "C1D5B04F19B45EA0F4FA65B57DFCA265D00FD80B",
        "VJYmUyg2v2jzpVje5iO8id1mMflg2DKpqR+NxpKmb2s",
        &[
            "142.4.215.43:443"
        ],
    ),
    // Nickname: thardes2
    fallback(
        "C47A245E3B12C82CB4ABBF283E66D478CCF8E240",
        "zOPJ+SFe6O9yXQ6ECFAe0YE2C1vNQfgHo8Xk9E6YHWE",
        &[
            "87.168.177.66:9001"
        ],
    ),
    // Nickname: MorbidHenry
    fallback(
        "83C81FF619BE11C46F0E98B27B437154779ED6CC",
        "J3qw/w2iEET4cfpew5aKXp5SMGewZ/7e8rfQKO+2ctk",
        &[
            "109.241.167.138:9001"
        ],
    ),
    // Nickname: rgiad
    fallback(
        "60E4C5E306D2DB22890EE24A09F9B6C30AF396A8",
        "hWHhdqGCKxwqTRgEko7AHGMfTmmUx7CH/8pBTeHGBFs",
        &[
            "198.180.150.9:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "FF3D6D040641D5A33ECC8B2B57D5BC59714C4209",
        "sFJOhUBTWUC87ysvSU/9iXKRuqLBKrrzcYHUKSKjLEg",
        &[
            "195.154.241.145:443"
        ],
    ),
    // Nickname: xdefTorEvey
    fallback(
        "69C4C2CFCF6B418636976B5FFC0140A3BE211312",
        "fLunK5DpMUzIx1NWyMRgiSi14EpoZaqgiBGeQUgDKeA",
        &[
            "178.62.251.184:9001",
            "[2a03:b0c0:2:d0::95:9001]:9001"
        ],
    ),
    // Nickname: ExplorationRelay
    fallback(
        "E300CEE2255A22B3DF52E798A3237D53AFAEC2F3",
        "lN77Bn2Rz+Vh3NQGKqx2K2Ubun935G2hWQH/NBnhnkA",
        &[
            "101.100.146.147:443"
        ],
    ),
    // Nickname: clanofxymox
    fallback(
        "BA0BA7A976F153DBB050266CD3D21F499FCB975D",
        "dsunp8P+F0Dl2XnVY9QtD54FFfN2sOwiK54gH9spoTA",
        &[
            "172.245.21.215:80"
        ],
    ),
    // Nickname: darknebula
    fallback(
        "04A28A62F27D9C4A60F9ED0C4264E98B988C65A3",
        "KL1Df2M+kN0YTy3rz4EqmQG489DcqUN4Hbaodm4skTY",
        &[
            "163.172.169.253:9001",
            "[2001:bc8:47a4:e0a::1]:9001"
        ],
    ),
    // Nickname: Fangio
    fallback(
        "65E40F7EDD28E2CF28684E30E0BAB7706819CFC3",
        "cgXu5tvmgUshrJMYDYMMegUKA23ICVMhdaGXQqbS6lg",
        &[
            "179.43.169.20:443"
        ],
    ),
    // Nickname: karfiol
    fallback(
        "96E095D5CDBFC3988DEB708EC155346472402C32",
        "JrC9nLNLwA89tpOceW6u+tOwh8gZmnto3rd5M1xg7sM",
        &[
            "109.70.100.11:443",
            "[2a03:e600:100::11]:443"
        ],
    ),
    // Nickname: INSRelay19at8443
    fallback(
        "885C7B6EB943068B762070E276E299319E5AB08C",
        "DodSIY4jKFppkPZTNaAWVi4dQ/KLYA+8+CygC1g5+/E",
        &[
            "140.78.100.19:8443"
        ],
    ),
    // Nickname: folo
    fallback(
        "389FBE96BA489D93AF2124EB9ABE339FC4C72F1B",
        "tK9yBuYFXnMRmY1Mhyk1jtvH63JYeIVfdm1C1LoYHkw",
        &[
            "185.117.118.15:9001"
        ],
    ),
    // Nickname: Alina
    fallback(
        "324E13FD795713BDD6E8B4DF02438742CA1FDBF1",
        "j3VL73xe4fCne2zNKUzgrkljkTTIEj2hCqNRg4pM4uY",
        &[
            "199.195.251.84:9001",
            "[2605:6400:10:80e::1]:9001"
        ],
    ),
    // Nickname: GreetingsFromTheNet
    fallback(
        "CF4DB0E0480FEB1E8F59C3D774EB9275283D579D",
        "OjF+0qnrGWFdepI9r4g3rA1rXVgFW9EENIeLDxgbBBs",
        &[
            "157.131.206.89:443"
        ],
    ),
    // Nickname: R1610091651
    fallback(
        "36EE8D47E570B8D5515460A9972F3CFD9EDFDFCE",
        "0bZjDfSE9MT1QJXGlrQspCSO225Q9g3YjhTA67bRqTs",
        &[
            "94.226.6.98:9443"
        ],
    ),
    // Nickname: shelob
    fallback(
        "687EFE281D08C65DE80935DEF63524EA053672B5",
        "dbnKHZX6x52T89sdeEgsdCmattl2A9ywF/LekL1kI78",
        &[
            "23.129.64.164:443",
            "[2620:18c:0:192::164]:443"
        ],
    ),
    // Nickname: MalfunctioningEddy
    fallback(
        "BCE86415B2EC28E449D360F632647E95D08F83C9",
        "BxE82WFdDk8mNKS7sr7ICcTIE6bGkyyK4OPah761bWo",
        &[
            "98.217.124.239:9001",
            "[2001:558:6017:16b:e5cc:c5c0:daaa:dd12]:9001"
        ],
    ),
    // Nickname: Aramis67
    fallback(
        "53C9F4954E7A7332BB0C610C5B8E04CA065AF29B",
        "FwglMw5mZH64JtjhgWS1HRi4vUC2sp2yQ6lSym5JUx0",
        &[
            "178.17.174.239:9001",
            "[2a00:1dc0:caff:126::a5c9]:9001"
        ],
    ),
    // Nickname: mitsuha
    fallback(
        "C0DAAAE5EE461BBE13945FE4B52F32ABDC6BC376",
        "MuaxcQ7uCMXw7A1Tf4YYQSRLK34+jj71dVNkFX272n8",
        &[
            "51.15.246.170:443",
            "[2001:bc8:47b0:1756::1]:443"
        ],
    ),
    // Nickname: relayon0130
    fallback(
        "7E281CD2C315C4F7A84BC7C8721C3BC974DDBFA3",
        "srmIRPIsRTpcqDT1q9LOrHVQcJukth6jgs/N+H0Y/kg",
        &[
            "185.220.101.19:10019",
            "[2a0b:f4c2::19]:10019"
        ],
    ),
    // Nickname: ProEscort
    fallback(
        "4C2C62B0828413159CBD076501C7D83BD0899893",
        "/c1KbBpSC9jO5nolTzvZfOCUnt4s6ogdsLM6UTmHgGs",
        &[
            "192.34.58.232:9004"
        ],
    ),
    // Nickname: Assange034us2
    fallback(
        "CF8CC4763298F77FF64DAF340D26D1BBF3362C5B",
        "gngQx/g7VykzIcTbhk0ER4w621dCDDLWASd+5tuNEK0",
        &[
            "162.212.158.82:9201"
        ],
    ),
    // Nickname: freedomRelay
    fallback(
        "B737FB6CBF7E514DD8D8B432A1497B9DBD0C45DA",
        "BZPRsMnwPGzNJ6446yMTVLGCddaydufx+6vD4ddAf3Q",
        &[
            "135.125.55.228:443"
        ],
    ),
    // Nickname: F3Netze
    fallback(
        "62F4994C6F3A5B3E590AEECE522591696C8DDEE2",
        "NXzwlgQRrJoDp3/PfOss1GrXD8DMVTVgIJPDN9vryAA",
        &[
            "185.220.100.241:9000",
            "[2a0b:f4c0:16c:15::1]:9000"
        ],
    ),
]
